#!/bin/bash
###
# orchestrate_runs_trigger_joint_gradmatch_metric_slurm.sh
#
# Slurm launcher for the federated_generate_labels_trigger_joint GRADMATCH_METRIC comparison
# ("relerr" vs "cosine", see run_module.py's run() docstring, "Gradient-mismatch penalty")
# generated by modules/federated_generate_labels_trigger_joint/gen_configs_gradmatch_metric.py
# -- a SEPARATE campaign from both orchestrate_runs_trigger_joint_slurm.sh (the main campaign)
# and orchestrate_runs_trigger_joint_sweep_slurm.sh (the OFAT hyperparameter sweep), so running
# one never interferes with the others.
#
# Chain, one Slurm job per cell, with afterok barriers between phases -- same job-pool/barrier
# mechanics as the two sibling scripts above:
#
#   [EXPERT]  train_expert                           (one per seed, shared across both metric
#        |                                             cells of that seed -- gradmatch_metric
#        |                                             doesn't affect expert training at all)
#   [GEN]     federated_generate_labels_trigger_joint (one per metric)
#        |
#   [FLIPS]   federated_select_flips
#        |
#   [USER]    federated_train_user                    (full budget sweep per cell, see
#                                                        gen_configs_gradmatch_metric.py's
#                                                        BUDGETS)
#
# Grid and directory layout below MUST match gen_configs_gradmatch_metric.py -- this script
# does NOT enumerate the axes itself, same by-hand-sync convention as the two sibling scripts.
# Run `python -m modules.federated_generate_labels_trigger_joint.gen_configs_gradmatch_metric \
# --dry-run` to print the authoritative cell list if in doubt.
#
# Usage:
#   1. Generate the configs (from BASE_DIR):
#        python -m modules.federated_generate_labels_trigger_joint.gen_configs_gradmatch_metric
#   2. Submit the campaign:
#        SLURM_ACCOUNT=<account> ./orchestrate_runs_trigger_joint_gradmatch_metric_slurm.sh
#        SLURM_ACCOUNT=<account> DRY_RUN=1 ./orchestrate_runs_trigger_joint_gradmatch_metric_slurm.sh
###

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="${BASE_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"
export BASE_DIR
cd "$BASE_DIR"

# shellcheck source=slurm_lib.sh
source "$SCRIPT_DIR/slurm_lib.sh"

DRY_RUN="${DRY_RUN:-0}"

EXPERT_TIME="${EXPERT_TIME:-0-00:10:00}"
GEN_TIME="${GEN_TIME:-1-00:00:00}"
FLIPS_TIME="${FLIPS_TIME:-00:10:00}"
USER_TIME="${USER_TIME:-0-01:00:00}"

# ---------------------------------------------------------------------------
# Fixed axes -- MUST match gen_configs_gradmatch_metric.py's own constants.
# ---------------------------------------------------------------------------
MODEL_FLAG="${MODEL_FLAG:-r32p}"
DATASET="${DATASET:-cifar}"
AGG_METHOD="${AGG_METHOD:-mean}"
NUM_POISONED="${NUM_POISONED:-1}"
NUM_HONESTS="${NUM_HONESTS:-0}"
read -ra SEEDS   <<< "${SEEDS:-0}"
read -ra BUDGETS <<< "${BUDGETS:-150 300 500 1000 2000 2500 5000}"

# The axis this comparison varies -- see gen_configs_gradmatch_metric.py's GRADMATCH_METRICS.
read -ra METRICS <<< "${METRICS:-relerr cosine}"

EXP_BASE_REL="${EXP_BASE_REL:-federated_experiments/threat_model_direct_trigger_joint_gradmatch_metric}"

# ---------------------------------------------------------------------------
# Helpers -- mirror gen_configs_gradmatch_metric.py's cell_name()/directory layout exactly.
# ---------------------------------------------------------------------------
MISSING=0

require_config() {
    local path="$1"
    if [ ! -f "experiments/$path/config.toml" ]; then
        echo "[CONFIG] missing: experiments/$path/config.toml" >&2
        MISSING=$((MISSING + 1))
    fi
}

cell_dir() {   # metric seed
    printf '%s/%s/%s/%svs%s/%s/%s/seed%s' "$EXP_BASE_REL" "$MODEL_FLAG" "$DATASET" \
        "$NUM_POISONED" "$NUM_HONESTS" "$AGG_METHOD" "$1" "$2"
}

# ---------------------------------------------------------------------------
# Build the job lists (seed -> metric -> budget), following gen_configs_gradmatch_metric.py's
# own nesting and directory layout. train_expert is per seed only (shared across both metric
# cells of that seed), so it is deduplicated instead of resubmitted per cell.
# ---------------------------------------------------------------------------
EXPERT_JOBS=()
GEN_JOBS=()
FLIPS_JOBS=()
USER_JOBS=()

for seed in "${SEEDS[@]}"; do
  expert_cfg="$EXP_BASE_REL/train_expert/${MODEL_FLAG}_1xs/seed${seed}"
  require_config "$expert_cfg"
  EXPERT_JOBS+=("python run_experiment.py $expert_cfg|gradmatch_expert_seed${seed}")

  for metric in "${METRICS[@]}"; do
    cell="$(cell_dir "$metric" "$seed")"
    job_tag="seed${seed}_${metric}"

    gen_cfg="$cell/gen_labels_trigger_joint"
    flips_cfg="$cell/select_flips"

    require_config "$gen_cfg"
    require_config "$flips_cfg"

    GEN_JOBS+=("python run_experiment.py $gen_cfg|gradmatch_gen_${job_tag}")
    FLIPS_JOBS+=("python run_experiment.py $flips_cfg|gradmatch_flips_${job_tag}")

    for budget in "${BUDGETS[@]}"; do
      user_cfg="$cell/train_user_${budget}"
      require_config "$user_cfg"
      USER_JOBS+=("python run_experiment.py $user_cfg|gradmatch_user_${job_tag}_${budget}")
    done
  done
done

if [ "$MISSING" -gt 0 ]; then
    echo "[ABORT] $MISSING config(s) missing -- generate them first:" >&2
    echo "        python -m modules.federated_generate_labels_trigger_joint.gen_configs_gradmatch_metric" >&2
    exit 1
fi

echo "[PLAN] module=federated_generate_labels_trigger_joint_gradmatch_metric exp_base=$EXP_BASE_REL"
echo "[PLAN] model=$MODEL_FLAG dataset=$DATASET agg=$AGG_METHOD ${NUM_POISONED}vs${NUM_HONESTS}"
echo "[PLAN] seeds=${SEEDS[*]} metrics=${METRICS[*]} budgets=${BUDGETS[*]}"
echo "[PLAN] cells=${#GEN_JOBS[@]} (=seeds x metrics), train_user jobs=${#USER_JOBS[@]}"
echo "[PLAN] partitions=${SLURM_PARTITIONS}"
echo "[PLAN] phases: EXPERT -> GEN -> FLIPS -> USER"

if [ "$DRY_RUN" = "1" ]; then
    echo "[DRY-RUN] nothing submitted."
    printf '[DRY-RUN] %s\n' "${EXPERT_JOBS[@]}"
    printf '[DRY-RUN] %s\n' "${GEN_JOBS[@]}"
    printf '[DRY-RUN] %s\n' "${FLIPS_JOBS[@]}"
    printf '[DRY-RUN] %s\n' "${USER_JOBS[@]}"
    exit 0
fi

preflight_slurm || exit 1

# ---------------------------------------------------------------------------
# Submit -- same job-pool/barrier pattern as the two sibling scripts.
# ---------------------------------------------------------------------------
TIME_PER_TASK="$EXPERT_TIME"
submit_job_pool_slurm EXPERT_JOBS "gradmatch_expert" "" || exit 1
expert_barrier=$(submit_barrier_slurm "gradmatch_barrier_expert" "afterok:$(join_job_ids "${SUBMITTED_JOB_IDS[@]}")") || exit 1
echo "[PHASE] EXPERT submitted (${#EXPERT_JOBS[@]} jobs) -> barrier $expert_barrier"

TIME_PER_TASK="$GEN_TIME"
submit_job_pool_slurm GEN_JOBS "gradmatch_gen" "afterok:$expert_barrier" || exit 1
gen_barrier=$(submit_barrier_slurm "gradmatch_barrier_gen" "afterok:$(join_job_ids "${SUBMITTED_JOB_IDS[@]}")") || exit 1
echo "[PHASE] GEN submitted (${#GEN_JOBS[@]} jobs) -> barrier $gen_barrier"

TIME_PER_TASK="$FLIPS_TIME"
submit_job_pool_slurm FLIPS_JOBS "gradmatch_flips" "afterok:$gen_barrier" || exit 1
flips_barrier=$(submit_barrier_slurm "gradmatch_barrier_flips" "afterok:$(join_job_ids "${SUBMITTED_JOB_IDS[@]}")") || exit 1
echo "[PHASE] FLIPS submitted (${#FLIPS_JOBS[@]} jobs) -> barrier $flips_barrier"

TIME_PER_TASK="$USER_TIME"
submit_job_pool_slurm USER_JOBS "gradmatch_user" "afterok:$flips_barrier" || exit 1
echo "[PHASE] USER submitted (${#USER_JOBS[@]} jobs)."

echo "[DONE] campaign submitted; job ids in $LOG_DIR/jobids_*.txt"
echo "[NOTE] this module builds a second-order graph (create_graph=True) on the"
echo "[NOTE] expert step: memory is ~2.6x the non-differentiable variant on a CPU"
echo "[NOTE] proxy measurement. Watch the first GEN job for OOM before the rest start."
