#!/bin/bash
###
# orchestrate_runs_trigger_joint_paper_main_campaign_slurm.sh
#
# Slurm launcher for the paper's main-results campaign, generated by
# modules/federated_generate_labels_trigger_joint/gen_configs_paper_main_campaign.py: the three
# finalist stealth configs (baseline / eps_0p50_lpips_0p1 / eps_16_255, pulled from
# gen_configs_old_objective_port_stealth_sweep.py's own STEALTH_GRID) x {r32p, convnext_micro} x
# {cifar, svhn} x 10 seeds, each deployed against BOTH a single_user (1-poisoned/0-honest/mean)
# branch and a federated_3vs7 branch swept over {mean, krum, multikrum, median, trmean} x budgets
# {0, 150, 300, 500, 1000, 2000, 2500, 5000}.
#
# Chain, with afterok barriers between phases (same job-pool/barrier mechanics as the sibling
# campaign scripts):
#
#   [BOOTSTRAP] train_expert, one per (model_flag, dataset, seed) -- SHARED across the 3 tags
#               (regularization changes don't affect the clean bootstrap expert)
#        |
#   [GEN]       federated_generate_labels_trigger_joint, one per (model_flag, dataset, tag, seed)
#        |
#   [FLIPS]     federated_select_flips, one single_user + one federated_3vs7 per GEN cell
#        |
#   [USER]      federated_train_user (single_user: mean x budgets; federated_3vs7: 5 agg_methods
#               x budgets)
#
# Grid MUST match gen_configs_paper_main_campaign.py -- this script does NOT enumerate its grid
# itself. Run
#   python -m modules.federated_generate_labels_trigger_joint.gen_configs_paper_main_campaign --print-grid
#   python -m modules.federated_generate_labels_trigger_joint.gen_configs_paper_main_campaign --print-tags
# to print the authoritative cell list / finalist tag list if in doubt.
#
# SCALE WARNING: this is the full paper campaign, not a preliminary sweep -- 40 BOOTSTRAP + 120
# GEN + 240 FLIPS + 5760 USER = 6160 jobs total (one `sbatch` submission each, see slurm_lib.sh's
# own header comment -- no shared allocation). Check your cluster's per-user MaxSubmitJobs/
# MaxJobs limits before submitting the whole thing at once; use the MODEL_FLAGS/DATASETS/SEEDS/
# STEALTH_TAGS env overrides below to stage the campaign in smaller slices (e.g. one model or
# dataset at a time) if needed.
#
# Usage:
#   1. Generate the configs (from BASE_DIR):
#        python -m modules.federated_generate_labels_trigger_joint.gen_configs_paper_main_campaign
#   2. Submit the campaign (optionally sliced, see SCALE WARNING above):
#        SLURM_ACCOUNT=<account> ./orchestrate_runs_trigger_joint_paper_main_campaign_slurm.sh
#        SLURM_ACCOUNT=<account> DRY_RUN=1 ./orchestrate_runs_trigger_joint_paper_main_campaign_slurm.sh
#        SLURM_ACCOUNT=<account> MODEL_FLAGS="r32p" DATASETS="cifar" ./orchestrate_runs_trigger_joint_paper_main_campaign_slurm.sh
#
#   Re-run just the USER phase (e.g. after a train_user-only config fix), skipping
#   BOOTSTRAP/GEN/FLIPS entirely and reusing already-materialized flips/triggers on disk:
#        SLURM_ACCOUNT=<account> USER_ONLY=1 ./orchestrate_runs_trigger_joint_paper_main_campaign_slurm.sh
#
#   Re-run just GEN+FLIPS+USER, skipping BOOTSTRAP (reusing existing expert checkpoints):
#        SLURM_ACCOUNT=<account> BOOTSTRAP_SKIP=1 ./orchestrate_runs_trigger_joint_paper_main_campaign_slurm.sh
###

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="${BASE_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"
export BASE_DIR
cd "$BASE_DIR"

# shellcheck source=slurm_lib.sh
source "$SCRIPT_DIR/slurm_lib.sh"

DRY_RUN="${DRY_RUN:-0}"
USER_ONLY="${USER_ONLY:-0}"
BOOTSTRAP_SKIP="${BOOTSTRAP_SKIP:-0}"

BOOTSTRAP_TIME="${BOOTSTRAP_TIME:-0-06:00:00}"
GEN_TIME="${GEN_TIME:-1-00:00:00}"
FLIPS_TIME="${FLIPS_TIME:-00:10:00}"
USER_TIME="${USER_TIME:-0-01:00:00}"

# ---------------------------------------------------------------------------
# Fixed axes -- MUST match gen_configs_paper_main_campaign.py's own constants. Every one of
# these is env-overridable so the campaign can be staged in smaller slices (see SCALE WARNING
# in the header comment above) -- e.g. MODEL_FLAGS="r32p" to submit only that model's cells.
# ---------------------------------------------------------------------------
read -ra MODEL_FLAGS <<< "${MODEL_FLAGS:-r32p convnext_micro}"
read -ra DATASETS <<< "${DATASETS:-cifar svhn}"
read -ra SEEDS <<< "${SEEDS:-0 1 2 3 4 5 6 7 8 9}"
# STEALTH_GRID's own three finalist tags (module docstring) -- keep in sync by hand; verify
# with --print-tags if in doubt.
read -ra STEALTH_TAGS <<< "${STEALTH_TAGS:-baseline eps_0p50_lpips_0p1 eps_16_255}"
read -ra DEPLOY_BUDGETS <<< "${DEPLOY_BUDGETS:-0 150 300 500 1000 2000 2500 5000}"
DEPLOY_SINGLE_USER_AGG="${DEPLOY_SINGLE_USER_AGG:-mean}"
read -ra DEPLOY_AGG_METHODS_FEDERATED <<< "${DEPLOY_AGG_METHODS_FEDERATED:-mean krum multikrum median trmean}"
FEDERATED_TAG="${FEDERATED_TAG:-federated_3vs7}"

EXP_BASE_REL="${EXP_BASE_REL:-federated_experiments/threat_model_direct_trigger_joint_paper_main_campaign}"

# ---------------------------------------------------------------------------
# Config / prerequisite presence check.
# ---------------------------------------------------------------------------
MISSING=0

require_config() {
    local path="$1"
    if [ ! -f "experiments/$path/config.toml" ]; then
        echo "[CONFIG] missing: experiments/$path/config.toml" >&2
        MISSING=$((MISSING + 1))
    fi
}

BOOTSTRAP_JOBS=()
for model in "${MODEL_FLAGS[@]}"; do
  for dataset in "${DATASETS[@]}"; do
    for seed in "${SEEDS[@]}"; do
      bootstrap_cfg="$EXP_BASE_REL/train_expert/${model}_${dataset}_1xs/seed${seed}"
      require_config "$bootstrap_cfg"
      BOOTSTRAP_JOBS+=("python run_experiment.py $bootstrap_cfg|paper_bootstrap_${model}_${dataset}_seed${seed}")
    done
  done
done

GEN_JOBS=()
FLIPS_JOBS=()
for model in "${MODEL_FLAGS[@]}"; do
  for dataset in "${DATASETS[@]}"; do
    for tag in "${STEALTH_TAGS[@]}"; do
      for seed in "${SEEDS[@]}"; do
        cell="$EXP_BASE_REL/$model/$dataset/$tag/seed${seed}"
        gen_cfg="$cell/gen_labels_trigger_joint"
        flips_cfg="$cell/select_flips"
        fed_flips_cfg="$cell/$FEDERATED_TAG/select_flips"
        require_config "$gen_cfg"
        require_config "$flips_cfg"
        require_config "$fed_flips_cfg"
        GEN_JOBS+=("python run_experiment.py $gen_cfg|paper_gen_${model}_${dataset}_${tag}_seed${seed}")
        FLIPS_JOBS+=("python run_experiment.py $flips_cfg|paper_flips_${model}_${dataset}_${tag}_seed${seed}")
        FLIPS_JOBS+=("python run_experiment.py $fed_flips_cfg|paper_flips_fed_${model}_${dataset}_${tag}_seed${seed}")
      done
    done
  done
done

USER_JOBS=()
for model in "${MODEL_FLAGS[@]}"; do
  for dataset in "${DATASETS[@]}"; do
    for tag in "${STEALTH_TAGS[@]}"; do
      for seed in "${SEEDS[@]}"; do
        cell="$EXP_BASE_REL/$model/$dataset/$tag/seed${seed}"
        for budget in "${DEPLOY_BUDGETS[@]}"; do
          user_cfg="$cell/$DEPLOY_SINGLE_USER_AGG/train_user_${budget}"
          require_config "$user_cfg"
          USER_JOBS+=("python run_experiment.py $user_cfg|paper_user_${model}_${dataset}_${tag}_seed${seed}_su_${budget}")
        done
        for agg_method in "${DEPLOY_AGG_METHODS_FEDERATED[@]}"; do
          for budget in "${DEPLOY_BUDGETS[@]}"; do
            user_cfg="$cell/$FEDERATED_TAG/$agg_method/train_user_${budget}"
            require_config "$user_cfg"
            USER_JOBS+=("python run_experiment.py $user_cfg|paper_user_${model}_${dataset}_${tag}_seed${seed}_${agg_method}_${budget}")
          done
        done
      done
    done
  done
done

if [ "$MISSING" -gt 0 ]; then
    echo "[ABORT] $MISSING config(s) missing -- generate them first:" >&2
    echo "        python -m modules.federated_generate_labels_trigger_joint.gen_configs_paper_main_campaign" >&2
    exit 1
fi

echo "[PLAN] campaign=paper_main_campaign exp_base=$EXP_BASE_REL"
echo "[PLAN] models=${MODEL_FLAGS[*]} datasets=${DATASETS[*]} seeds=${#SEEDS[@]} (${SEEDS[*]}) tags=${STEALTH_TAGS[*]}"
echo "[PLAN] deployment: single_user agg=$DEPLOY_SINGLE_USER_AGG, federated($FEDERATED_TAG) agg_methods=${DEPLOY_AGG_METHODS_FEDERATED[*]}, budgets=${DEPLOY_BUDGETS[*]}"
echo "[PLAN] bootstrap cells=${#BOOTSTRAP_JOBS[@]} gen cells=${#GEN_JOBS[@]} flips cells=${#FLIPS_JOBS[@]} user cells=${#USER_JOBS[@]}"
echo "[PLAN] partitions=${SLURM_PARTITIONS}"
if [ "$USER_ONLY" = "1" ]; then
    echo "[PLAN] phases: USER only (USER_ONLY=1 -- reusing existing BOOTSTRAP/GEN/FLIPS outputs on disk)"
elif [ "$BOOTSTRAP_SKIP" = "1" ]; then
    echo "[PLAN] phases: GEN -> FLIPS -> USER (BOOTSTRAP_SKIP=1 -- reusing existing bootstrap checkpoints)"
else
    echo "[PLAN] phases: BOOTSTRAP -> GEN -> FLIPS -> USER"
fi

if [ "$DRY_RUN" = "1" ]; then
    echo "[DRY-RUN] nothing submitted."
    if [ "$USER_ONLY" != "1" ]; then
        if [ "$BOOTSTRAP_SKIP" != "1" ]; then
            printf '[DRY-RUN] %s\n' "${BOOTSTRAP_JOBS[@]}"
        fi
        printf '[DRY-RUN] %s\n' "${GEN_JOBS[@]}"
        printf '[DRY-RUN] %s\n' "${FLIPS_JOBS[@]}"
    fi
    printf '[DRY-RUN] %s\n' "${USER_JOBS[@]}"
    exit 0
fi

preflight_slurm || exit 1

# ---------------------------------------------------------------------------
# Submit -- same job-pool/barrier pattern as the sibling campaign scripts.
# ---------------------------------------------------------------------------
if [ "$USER_ONLY" = "1" ]; then
    TIME_PER_TASK="$USER_TIME"
    submit_job_pool_slurm USER_JOBS "paper_user" || exit 1
    echo "[PHASE] USER submitted (${#USER_JOBS[@]} jobs), no dependency (USER_ONLY=1)."
else
    gen_dep=""
    if [ "$BOOTSTRAP_SKIP" != "1" ]; then
        TIME_PER_TASK="$BOOTSTRAP_TIME"
        submit_job_pool_slurm BOOTSTRAP_JOBS "paper_bootstrap" || exit 1
        bootstrap_barrier=$(submit_barrier_slurm "paper_barrier_bootstrap" "afterok:$(join_job_ids "${SUBMITTED_JOB_IDS[@]}")") || exit 1
        echo "[PHASE] BOOTSTRAP submitted (${#BOOTSTRAP_JOBS[@]} jobs) -> barrier $bootstrap_barrier"
        gen_dep="afterok:$bootstrap_barrier"
    else
        echo "[PHASE] BOOTSTRAP skipped (BOOTSTRAP_SKIP=1)."
    fi

    TIME_PER_TASK="$GEN_TIME"
    submit_job_pool_slurm GEN_JOBS "paper_gen" "$gen_dep" || exit 1
    gen_barrier=$(submit_barrier_slurm "paper_barrier_gen" "afterok:$(join_job_ids "${SUBMITTED_JOB_IDS[@]}")") || exit 1
    echo "[PHASE] GEN submitted (${#GEN_JOBS[@]} jobs) -> barrier $gen_barrier"

    TIME_PER_TASK="$FLIPS_TIME"
    submit_job_pool_slurm FLIPS_JOBS "paper_flips" "afterok:$gen_barrier" || exit 1
    flips_barrier=$(submit_barrier_slurm "paper_barrier_flips" "afterok:$(join_job_ids "${SUBMITTED_JOB_IDS[@]}")") || exit 1
    echo "[PHASE] FLIPS submitted (${#FLIPS_JOBS[@]} jobs) -> barrier $flips_barrier"

    TIME_PER_TASK="$USER_TIME"
    submit_job_pool_slurm USER_JOBS "paper_user" "afterok:$flips_barrier" || exit 1
    echo "[PHASE] USER submitted (${#USER_JOBS[@]} jobs)."
fi

echo "[DONE] campaign submitted; job ids in $LOG_DIR/jobids_*.txt"
echo "[NOTE] this module builds a second-order graph (create_graph=True) on the"
echo "[NOTE] expert step, with n_checkpoints_per_step=5 DISTINCT checkpoints held"
echo "[NOTE] simultaneously -- watch the first GEN job for OOM before the rest start."
