#!/bin/bash
###
# orchestrate_runs_trigger_joint_sweep_slurm.sh
#
# Slurm launcher for the federated_generate_labels_trigger_joint HYPERPARAMETER SWEEP
# generated by modules/federated_generate_labels_trigger_joint/gen_configs_sweep.py -- a
# SEPARATE campaign from orchestrate_runs_trigger_joint_slurm.sh (the main campaign), so
# running one never interferes with the other.
#
# Chain, one Slurm job per cell, with afterok barriers between phases -- same
# job-pool/barrier mechanics as orchestrate_runs_trigger_joint_slurm.sh:
#
#   [EXPERT]  train_expert                           (one per seed, shared across every cell
#        |                                             of that seed -- sweep axes don't affect
#        |                                             expert training at all)
#   [GEN]     federated_generate_labels_trigger_joint (one per sweep cell)
#        |
#   [FLIPS]   federated_select_flips
#        |
#   [USER]    federated_train_user                    (single budget per cell, see
#                                                        gen_configs_sweep.py's BUDGETS)
#
# Sweep cells (tags) and directory layout below MUST match gen_configs_sweep.py -- this
# script does NOT enumerate the sweep axes itself, it lists the cell tags by hand (kept in
# sync manually, same convention as orchestrate_runs_trigger_joint_slurm.sh's grid comment).
# Run `python -m modules.federated_generate_labels_trigger_joint.gen_configs_sweep --dry-run`
# to print the authoritative cell list if in doubt.
#
# Multi-partition: set SLURM_PARTITIONS (space-separated) to spread jobs round-robin across
# more than one partition and use more GPUs at once, e.g.:
#   SLURM_PARTITIONS="cypress_dgx other_dgx_partition" SLURM_ACCOUNT=<account> \
#       ./orchestrate_runs_trigger_joint_sweep_slurm.sh
# (implemented once in slurm_lib.sh -- see submit_job_pool_slurm -- so both this script and
# orchestrate_runs_trigger_joint_slurm.sh get it automatically; SLURM_PARTITION, singular,
# still works unchanged for a single partition.)
#
# Usage:
#   1. Generate the configs (from BASE_DIR):
#        python -m modules.federated_generate_labels_trigger_joint.gen_configs_sweep
#   2. Submit the campaign:
#        SLURM_ACCOUNT=<account> ./orchestrate_runs_trigger_joint_sweep_slurm.sh
#        SLURM_ACCOUNT=<account> DRY_RUN=1 ./orchestrate_runs_trigger_joint_sweep_slurm.sh
###

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# BASE_DIR must be the FLIP repo root -- this script lives one level below it
# (orchestrate_slurm/, moved here 2026-08-30; it used to sit at the repo root, where
# SCRIPT_DIR alone was correct). Every relative path below (experiments/..., python
# run_experiment.py ...) is resolved against BASE_DIR after the cd below.
BASE_DIR="${BASE_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"
export BASE_DIR
cd "$BASE_DIR"

# shellcheck source=slurm_lib.sh
source "$SCRIPT_DIR/slurm_lib.sh"

DRY_RUN="${DRY_RUN:-0}"

EXPERT_TIME="${EXPERT_TIME:-0-00:10:00}"
GEN_TIME="${GEN_TIME:-1-00:00:00}"
FLIPS_TIME="${FLIPS_TIME:-00:10:00}"
USER_TIME="${USER_TIME:-0-01:00:00}"

# ---------------------------------------------------------------------------
# Fixed axes -- MUST match gen_configs_sweep.py's own constants.
# ---------------------------------------------------------------------------
MODEL_FLAG="${MODEL_FLAG:-r32p}"
DATASET="${DATASET:-cifar}"
NUM_POISONED="${NUM_POISONED:-1}"
NUM_HONESTS="${NUM_HONESTS:-0}"
read -ra SEEDS <<< "${SEEDS:-0}"
BUDGET="${BUDGET:-1500}"

EXP_BASE_REL="${EXP_BASE_REL:-federated_experiments/threat_model_direct_trigger_joint_sweep}"

# ---------------------------------------------------------------------------
# Sweep cell tags -- one "baseline" cell plus one OFAT cell per (axis, value) that gen_configs_
# sweep.py's build_cells() actually generates. Kept in sync BY HAND with gen_configs_sweep.py's
# BASELINE/SWEEP_AXES -- re-copy this list whenever those change (see the --dry-run note above
# to get the authoritative list back out of the generator itself).
# ---------------------------------------------------------------------------
read -ra CELL_TAGS <<< "${CELL_TAGS:-baseline \
lr_delta_0p001 lr_delta_0p005 lr_delta_0p05 lr_delta_0p1 \
lambda_bd_0p5 lambda_bd_1p0 lambda_bd_4p0 lambda_bd_8p0 \
n_iterations_10 n_iterations_25 n_iterations_40 \
epsilon_0p05 epsilon_0p1 epsilon_0p3 \
gamma_stealth_0p0 gamma_stealth_0p1 gamma_stealth_1p0 \
lambda_delta_0p01 lambda_delta_0p1 lambda_delta_1p0 \
trigger_constraint_projection \
align_kappa_0p0 align_kappa_0p6 \
lambda_align_0p0 lambda_align_1p0 \
lambda_mag_0p0 lambda_mag_1p0 \
delta_min_frac_0p0 delta_min_frac_0p05}"

# ---------------------------------------------------------------------------
# Helpers -- mirror gen_configs_sweep.py's directory layout exactly.
# ---------------------------------------------------------------------------
MISSING=0

require_config() {
    local path="$1"
    if [ ! -f "experiments/$path/config.toml" ]; then
        echo "[CONFIG] missing: experiments/$path/config.toml" >&2
        MISSING=$((MISSING + 1))
    fi
}

cell_dir() {   # seed tag
    printf '%s/%s/%s/%svs%s/seed%s/%s' "$EXP_BASE_REL" "$MODEL_FLAG" "$DATASET" \
        "$NUM_POISONED" "$NUM_HONESTS" "$1" "$2"
}

# ---------------------------------------------------------------------------
# Build the job lists (seed -> tag), following gen_configs_sweep.py's own nesting and
# directory layout. train_expert is per seed only (shared across every cell of that seed),
# so it is deduplicated instead of resubmitted per cell.
# ---------------------------------------------------------------------------
EXPERT_JOBS=()
GEN_JOBS=()
FLIPS_JOBS=()
USER_JOBS=()

for seed in "${SEEDS[@]}"; do
  expert_cfg="$EXP_BASE_REL/train_expert/${MODEL_FLAG}_1xs/seed${seed}"
  require_config "$expert_cfg"
  EXPERT_JOBS+=("python run_experiment.py $expert_cfg|sweep_expert_seed${seed}")

  for tag in "${CELL_TAGS[@]}"; do
    cell="$(cell_dir "$seed" "$tag")"
    job_tag="seed${seed}_${tag}"

    gen_cfg="$cell/gen_labels_trigger_joint"
    flips_cfg="$cell/select_flips"
    user_cfg="$cell/train_user_${BUDGET}"

    require_config "$gen_cfg"
    require_config "$flips_cfg"
    require_config "$user_cfg"

    GEN_JOBS+=("python run_experiment.py $gen_cfg|sweep_gen_${job_tag}")
    FLIPS_JOBS+=("python run_experiment.py $flips_cfg|sweep_flips_${job_tag}")
    USER_JOBS+=("python run_experiment.py $user_cfg|sweep_user_${job_tag}")
  done
done

if [ "$MISSING" -gt 0 ]; then
    echo "[ABORT] $MISSING config(s) missing -- generate them first:" >&2
    echo "        python -m modules.federated_generate_labels_trigger_joint.gen_configs_sweep" >&2
    exit 1
fi

echo "[PLAN] module=federated_generate_labels_trigger_joint_sweep exp_base=$EXP_BASE_REL"
echo "[PLAN] model=$MODEL_FLAG dataset=$DATASET ${NUM_POISONED}vs${NUM_HONESTS} budget=$BUDGET"
echo "[PLAN] seeds=${SEEDS[*]} cells=${#CELL_TAGS[@]} (=${#GEN_JOBS[@]} gen/flips/user jobs)"
echo "[PLAN] partitions=${SLURM_PARTITIONS}"
echo "[PLAN] phases: EXPERT -> GEN -> FLIPS -> USER"

if [ "$DRY_RUN" = "1" ]; then
    echo "[DRY-RUN] nothing submitted."
    printf '[DRY-RUN] %s\n' "${EXPERT_JOBS[@]}"
    printf '[DRY-RUN] %s\n' "${GEN_JOBS[@]}"
    printf '[DRY-RUN] %s\n' "${FLIPS_JOBS[@]}"
    printf '[DRY-RUN] %s\n' "${USER_JOBS[@]}"
    exit 0
fi

preflight_slurm || exit 1

# ---------------------------------------------------------------------------
# Submit -- same job-pool/barrier pattern as orchestrate_runs_trigger_joint_slurm.sh.
# ---------------------------------------------------------------------------
TIME_PER_TASK="$EXPERT_TIME"
submit_job_pool_slurm EXPERT_JOBS "sweep_expert" "" || exit 1
expert_barrier=$(submit_barrier_slurm "sweep_barrier_expert" "afterok:$(join_job_ids "${SUBMITTED_JOB_IDS[@]}")") || exit 1
echo "[PHASE] EXPERT submitted (${#EXPERT_JOBS[@]} jobs) -> barrier $expert_barrier"

TIME_PER_TASK="$GEN_TIME"
submit_job_pool_slurm GEN_JOBS "sweep_gen" "afterok:$expert_barrier" || exit 1
gen_barrier=$(submit_barrier_slurm "sweep_barrier_gen" "afterok:$(join_job_ids "${SUBMITTED_JOB_IDS[@]}")") || exit 1
echo "[PHASE] GEN submitted (${#GEN_JOBS[@]} jobs) -> barrier $gen_barrier"

TIME_PER_TASK="$FLIPS_TIME"
submit_job_pool_slurm FLIPS_JOBS "sweep_flips" "afterok:$gen_barrier" || exit 1
flips_barrier=$(submit_barrier_slurm "sweep_barrier_flips" "afterok:$(join_job_ids "${SUBMITTED_JOB_IDS[@]}")") || exit 1
echo "[PHASE] FLIPS submitted (${#FLIPS_JOBS[@]} jobs) -> barrier $flips_barrier"

TIME_PER_TASK="$USER_TIME"
submit_job_pool_slurm USER_JOBS "sweep_user" "afterok:$flips_barrier" || exit 1
echo "[PHASE] USER submitted (${#USER_JOBS[@]} jobs)."

echo "[DONE] sweep submitted; job ids in $LOG_DIR/jobids_*.txt"
