#!/bin/bash
###
# orchestrate_runs_trigger_joint_old_objective_port_slurm.sh
#
# Slurm launcher for the old-objective-port campaign generated by
# modules/federated_generate_labels_trigger_joint/gen_configs_old_objective_port.py: ports the
# old federated_optimizing_trigger objective (trigger_penalty, cos(delta,mu_target)+1) into
# federated_generate_labels_trigger_joint under the exact generation-time config that broke
# every robust aggregator in the old module (num_honests=0, num_poisoned=1, agg_method="mean"),
# then evaluates the resulting trigger against a realistic deployment (3 poisoned/7 honest)
# under THREE victim aggregators -- mean, trmean, multikrum -- and three budgets.
#
# Chain, with afterok barriers between phases (same job-pool/barrier mechanics as the sibling
# *_compare_slurm.sh scripts):
#
#   [BOOTSTRAP] train_expert (poisoner="1xs", one-off)
#        |
#   [GEN]       federated_generate_labels_trigger_joint (one-off, generation-time config fixed)
#        |
#   [FLIPS]     federated_select_flips (one-off, shared across every agg_method)
#        |
#   [USER]      federated_train_user (agg_method x budget = 3 x 3 = 9 jobs)
#
# Grid MUST match gen_configs_old_objective_port.py -- this script does NOT enumerate the axes
# itself. Run `python -m modules.federated_generate_labels_trigger_joint.gen_configs_old_objective_port
# --print-grid` to print the authoritative cell list if in doubt.
#
# Usage:
#   1. Generate the configs (from BASE_DIR):
#        python -m modules.federated_generate_labels_trigger_joint.gen_configs_old_objective_port
#   2. Submit the campaign:
#        SLURM_ACCOUNT=<account> ./orchestrate_runs_trigger_joint_old_objective_port_slurm.sh
#        SLURM_ACCOUNT=<account> DRY_RUN=1 ./orchestrate_runs_trigger_joint_old_objective_port_slurm.sh
###

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="${BASE_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"
export BASE_DIR
cd "$BASE_DIR"

# shellcheck source=slurm_lib.sh
source "$SCRIPT_DIR/slurm_lib.sh"

DRY_RUN="${DRY_RUN:-0}"

BOOTSTRAP_TIME="${BOOTSTRAP_TIME:-0-00:10:00}"
GEN_TIME="${GEN_TIME:-1-00:00:00}"
FLIPS_TIME="${FLIPS_TIME:-00:10:00}"
USER_TIME="${USER_TIME:-0-01:00:00}"

# ---------------------------------------------------------------------------
# Fixed axes -- MUST match gen_configs_old_objective_port.py's own constants.
# ---------------------------------------------------------------------------
MODEL_FLAG="${MODEL_FLAG:-r32p}"
DATASET="${DATASET:-cifar}"
read -ra DEPLOY_AGG_METHODS <<< "${DEPLOY_AGG_METHODS:-mean trmean multikrum}"
read -ra DEPLOY_BUDGETS <<< "${DEPLOY_BUDGETS:-500 1500 5000}"

EXP_BASE_REL="${EXP_BASE_REL:-federated_experiments/threat_model_direct_trigger_joint_old_objective_port}"
CELL_BASE_REL="$EXP_BASE_REL/$MODEL_FLAG/$DATASET"

# ---------------------------------------------------------------------------
# Config presence check.
# ---------------------------------------------------------------------------
MISSING=0

require_config() {
    local path="$1"
    if [ ! -f "experiments/$path/config.toml" ]; then
        echo "[CONFIG] missing: experiments/$path/config.toml" >&2
        MISSING=$((MISSING + 1))
    fi
}

BOOTSTRAP_CFG="$EXP_BASE_REL/train_expert/${MODEL_FLAG}_1xs_bootstrap"
GEN_CFG="$CELL_BASE_REL/gen_labels_trigger_joint"
FLIPS_CFG="$CELL_BASE_REL/select_flips"

require_config "$BOOTSTRAP_CFG"
require_config "$GEN_CFG"
require_config "$FLIPS_CFG"

USER_JOBS=()
for agg_method in "${DEPLOY_AGG_METHODS[@]}"; do
  for budget in "${DEPLOY_BUDGETS[@]}"; do
    user_cfg="$CELL_BASE_REL/$agg_method/train_user_${budget}"
    require_config "$user_cfg"
    USER_JOBS+=("python run_experiment.py $user_cfg|old_port_user_${agg_method}_${budget}")
  done
done

if [ "$MISSING" -gt 0 ]; then
    echo "[ABORT] $MISSING config(s) missing -- generate them first:" >&2
    echo "        python -m modules.federated_generate_labels_trigger_joint.gen_configs_old_objective_port" >&2
    exit 1
fi

echo "[PLAN] campaign=old_objective_port exp_base=$EXP_BASE_REL"
echo "[PLAN] model=$MODEL_FLAG dataset=$DATASET (generation-time: num_honests=0/num_poisoned=1/agg=mean, FIXED)"
echo "[PLAN] deployment sweep: agg_methods=${DEPLOY_AGG_METHODS[*]} budgets=${DEPLOY_BUDGETS[*]} (num_honests=7/num_poisoned=3)"
echo "[PLAN] user cells=${#USER_JOBS[@]} (=agg_methods x budgets)"
echo "[PLAN] partitions=${SLURM_PARTITIONS}"
echo "[PLAN] phases: BOOTSTRAP -> GEN -> FLIPS -> USER"

if [ "$DRY_RUN" = "1" ]; then
    echo "[DRY-RUN] nothing submitted."
    echo "[DRY-RUN] python run_experiment.py $BOOTSTRAP_CFG"
    echo "[DRY-RUN] python run_experiment.py $GEN_CFG"
    echo "[DRY-RUN] python run_experiment.py $FLIPS_CFG"
    printf '[DRY-RUN] %s\n' "${USER_JOBS[@]}"
    exit 0
fi

preflight_slurm || exit 1

# ---------------------------------------------------------------------------
# Submit -- same job-pool/barrier pattern as the sibling campaign scripts.
# ---------------------------------------------------------------------------
TIME_PER_TASK="$BOOTSTRAP_TIME"
BOOTSTRAP_JOBS=("python run_experiment.py $BOOTSTRAP_CFG|old_port_bootstrap")
submit_job_pool_slurm BOOTSTRAP_JOBS "old_port_bootstrap" || exit 1
bootstrap_barrier=$(submit_barrier_slurm "old_port_barrier_bootstrap" "afterok:$(join_job_ids "${SUBMITTED_JOB_IDS[@]}")") || exit 1
echo "[PHASE] BOOTSTRAP submitted -> barrier $bootstrap_barrier"

TIME_PER_TASK="$GEN_TIME"
GEN_JOBS=("python run_experiment.py $GEN_CFG|old_port_gen")
submit_job_pool_slurm GEN_JOBS "old_port_gen" "afterok:$bootstrap_barrier" || exit 1
gen_barrier=$(submit_barrier_slurm "old_port_barrier_gen" "afterok:$(join_job_ids "${SUBMITTED_JOB_IDS[@]}")") || exit 1
echo "[PHASE] GEN submitted -> barrier $gen_barrier"

TIME_PER_TASK="$FLIPS_TIME"
FLIPS_JOBS=("python run_experiment.py $FLIPS_CFG|old_port_flips")
submit_job_pool_slurm FLIPS_JOBS "old_port_flips" "afterok:$gen_barrier" || exit 1
flips_barrier=$(submit_barrier_slurm "old_port_barrier_flips" "afterok:$(join_job_ids "${SUBMITTED_JOB_IDS[@]}")") || exit 1
echo "[PHASE] FLIPS submitted -> barrier $flips_barrier"

TIME_PER_TASK="$USER_TIME"
submit_job_pool_slurm USER_JOBS "old_port_user" "afterok:$flips_barrier" || exit 1
echo "[PHASE] USER submitted (${#USER_JOBS[@]} jobs)."

echo "[DONE] campaign submitted; job ids in $LOG_DIR/jobids_*.txt"
echo "[NOTE] this module builds a second-order graph (create_graph=True) on the"
echo "[NOTE] expert step, now with n_checkpoints_per_step=5 DISTINCT checkpoints held"
echo "[NOTE] simultaneously -- watch the GEN job for OOM before the USER phase starts."
