#!/bin/bash
###
# orchestrate_runs_trigger_joint_old_objective_port_stealth_sweep_slurm.sh
#
# Slurm launcher for the stealth-regularization sweep generated by
# modules/federated_generate_labels_trigger_joint/gen_configs_old_objective_port_stealth_sweep.py:
# one-at-a-time variants (epsilon / lambda_tv / lambda_lpips / lambda_penalty) around the
# old-objective-port winning config (num_honests=0/num_poisoned=1/agg_method="mean" at
# generation time, lambda_joint=1.0, iterations=25 -- see that generator's own docstring for
# why this differs from gen_configs_old_objective_port.py's own, since-drifted template
# defaults), each deployed against the SAME 3-poisoned/7-honest x {mean, trmean, multikrum} x
# {500, 1500, 5000} grid gen_configs_old_objective_port.py itself uses.
#
# Chain, with afterok barriers between phases (same job-pool/barrier mechanics as
# orchestrate_runs_trigger_joint_old_objective_port_slurm.sh):
#
#   [BOOTSTRAP] REUSED, not resubmitted -- this campaign's train_expert bootstrap is IDENTICAL
#               to gen_configs_old_objective_port.py's own (poisoner="1xs", independent of every
#               regularization knob this sweep varies). Run
#               orchestrate_runs_trigger_joint_old_objective_port_slurm.sh's own BOOTSTRAP phase
#               (or plain `python run_experiment.py <its BOOTSTRAP_CFG>`) once, first, if you
#               have not already -- this script's preflight check below verifies the checkpoint
#               directory exists and aborts with a clear message if not.
#        |
#   [GEN]       federated_generate_labels_trigger_joint, one job per STEALTH_GRID tag
#        |
#   [FLIPS]     federated_select_flips, one job per tag (shared across every agg_method)
#        |
#   [USER]      federated_train_user (tag x agg_method x budget jobs)
#
# Grid MUST match gen_configs_old_objective_port_stealth_sweep.py -- this script does NOT
# enumerate STEALTH_GRID itself. Run
#   python -m modules.federated_generate_labels_trigger_joint.gen_configs_old_objective_port_stealth_sweep --print-tags
#   python -m modules.federated_generate_labels_trigger_joint.gen_configs_old_objective_port_stealth_sweep --print-grid
# to print the authoritative tag list / full (tag, agg_method, budget) cell list if in doubt.
#
# Usage:
#   1. Generate the configs (from BASE_DIR):
#        python -m modules.federated_generate_labels_trigger_joint.gen_configs_old_objective_port_stealth_sweep
#   2. Submit the campaign:
#        SLURM_ACCOUNT=<account> ./orchestrate_runs_trigger_joint_old_objective_port_stealth_sweep_slurm.sh
#        SLURM_ACCOUNT=<account> DRY_RUN=1 ./orchestrate_runs_trigger_joint_old_objective_port_stealth_sweep_slurm.sh
#
#   Re-run just the USER phase (e.g. after a train_user-only config fix), skipping
#   GEN/FLIPS entirely and reusing already-materialized flips/triggers on disk:
#        SLURM_ACCOUNT=<account> USER_ONLY=1 ./orchestrate_runs_trigger_joint_old_objective_port_stealth_sweep_slurm.sh
###

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="${BASE_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"
export BASE_DIR
cd "$BASE_DIR"

# shellcheck source=slurm_lib.sh
source "$SCRIPT_DIR/slurm_lib.sh"

DRY_RUN="${DRY_RUN:-0}"
USER_ONLY="${USER_ONLY:-0}"

GEN_TIME="${GEN_TIME:-1-00:00:00}"
FLIPS_TIME="${FLIPS_TIME:-00:10:00}"
USER_TIME="${USER_TIME:-0-01:00:00}"

# ---------------------------------------------------------------------------
# Fixed axes -- MUST match gen_configs_old_objective_port_stealth_sweep.py's own constants.
# ---------------------------------------------------------------------------
MODEL_FLAG="${MODEL_FLAG:-r32p}"
DATASET="${DATASET:-cifar}"
read -ra DEPLOY_AGG_METHODS <<< "${DEPLOY_AGG_METHODS:-mean trmean multikrum}"
read -ra DEPLOY_BUDGETS <<< "${DEPLOY_BUDGETS:-500 1500 5000}"
# STEALTH_GRID's own tags (module docstring) -- keep in sync by hand, same convention as
# DEPLOY_AGG_METHODS/DEPLOY_BUDGETS above; verify with --print-tags if in doubt.
read -ra STEALTH_TAGS <<< "${STEALTH_TAGS:-baseline eps_0p50 eps_0p25 eps_0p125 tv_0p01 tv_0p05 tv_0p10 lpips_0p1 lpips_0p5 lpips_1p0 penalty_0p5 penalty_2p0 eps_0p50_lpips_0p1 eps_0p375_lpips_0p2 eps_0p50_lpips_0p2 eps_16_255_lpips_1p0 eps_16_255_lpips_0p5 eps_16_255}"

EXP_BASE_REL="${EXP_BASE_REL:-federated_experiments/threat_model_direct_trigger_joint_old_objective_port_stealth_sweep}"
CELL_BASE_REL="$EXP_BASE_REL/$MODEL_FLAG/$DATASET"

BOOTSTRAP_OUTPUT_DIR="${BOOTSTRAP_OUTPUT_DIR:-$BASE_DIR/out/checkpoints/old_objective_port_r32p_1xs_bootstrap}"

# ---------------------------------------------------------------------------
# Config / prerequisite presence check.
# ---------------------------------------------------------------------------
MISSING=0

require_config() {
    local path="$1"
    if [ ! -f "experiments/$path/config.toml" ]; then
        echo "[CONFIG] missing: experiments/$path/config.toml" >&2
        MISSING=$((MISSING + 1))
    fi
}

if [ ! -d "$BOOTSTRAP_OUTPUT_DIR/0" ]; then
    echo "[ABORT] bootstrap expert checkpoint dir not found: $BOOTSTRAP_OUTPUT_DIR/0" >&2
    echo "        Run gen_configs_old_objective_port's own BOOTSTRAP phase first (see this" >&2
    echo "        script's own header comment) -- this campaign reuses that checkpoint" >&2
    echo "        unchanged, it does not retrain it." >&2
    exit 1
fi

GEN_JOBS=()
FLIPS_JOBS=()
declare -A FLIPS_DIR_BY_TAG
for tag in "${STEALTH_TAGS[@]}"; do
    gen_cfg="$CELL_BASE_REL/$tag/gen_labels_trigger_joint"
    flips_cfg="$CELL_BASE_REL/$tag/select_flips"
    require_config "$gen_cfg"
    require_config "$flips_cfg"
    GEN_JOBS+=("python run_experiment.py $gen_cfg|stealth_gen_${tag}")
    FLIPS_JOBS+=("python run_experiment.py $flips_cfg|stealth_flips_${tag}")
done

USER_JOBS=()
for tag in "${STEALTH_TAGS[@]}"; do
  for agg_method in "${DEPLOY_AGG_METHODS[@]}"; do
    for budget in "${DEPLOY_BUDGETS[@]}"; do
      user_cfg="$CELL_BASE_REL/$tag/$agg_method/train_user_${budget}"
      require_config "$user_cfg"
      USER_JOBS+=("python run_experiment.py $user_cfg|stealth_user_${tag}_${agg_method}_${budget}")
    done
  done
done

if [ "$MISSING" -gt 0 ]; then
    echo "[ABORT] $MISSING config(s) missing -- generate them first:" >&2
    echo "        python -m modules.federated_generate_labels_trigger_joint.gen_configs_old_objective_port_stealth_sweep" >&2
    exit 1
fi

echo "[PLAN] campaign=old_objective_port_stealth_sweep exp_base=$EXP_BASE_REL"
echo "[PLAN] model=$MODEL_FLAG dataset=$DATASET (generation-time: num_honests=0/num_poisoned=1/agg=mean, FIXED)"
echo "[PLAN] stealth tags=${#STEALTH_TAGS[@]} (${STEALTH_TAGS[*]})"
echo "[PLAN] deployment sweep: agg_methods=${DEPLOY_AGG_METHODS[*]} budgets=${DEPLOY_BUDGETS[*]} (num_honests=7/num_poisoned=3)"
echo "[PLAN] user cells=${#USER_JOBS[@]} (=tags x agg_methods x budgets)"
echo "[PLAN] partitions=${SLURM_PARTITIONS}"
if [ "$USER_ONLY" = "1" ]; then
    echo "[PLAN] phases: USER only (USER_ONLY=1 -- reusing existing GEN/FLIPS outputs on disk)"
else
    echo "[PLAN] phases: GEN -> FLIPS -> USER (BOOTSTRAP reused, see header)"
fi

if [ "$DRY_RUN" = "1" ]; then
    echo "[DRY-RUN] nothing submitted."
    if [ "$USER_ONLY" != "1" ]; then
        printf '[DRY-RUN] %s\n' "${GEN_JOBS[@]}"
        printf '[DRY-RUN] %s\n' "${FLIPS_JOBS[@]}"
    fi
    printf '[DRY-RUN] %s\n' "${USER_JOBS[@]}"
    exit 0
fi

preflight_slurm || exit 1

# ---------------------------------------------------------------------------
# Submit -- same job-pool/barrier pattern as the sibling campaign scripts.
# ---------------------------------------------------------------------------
if [ "$USER_ONLY" = "1" ]; then
    TIME_PER_TASK="$USER_TIME"
    submit_job_pool_slurm USER_JOBS "stealth_user" || exit 1
    echo "[PHASE] USER submitted (${#USER_JOBS[@]} jobs), no dependency (USER_ONLY=1)."
else
    TIME_PER_TASK="$GEN_TIME"
    submit_job_pool_slurm GEN_JOBS "stealth_gen" || exit 1
    gen_barrier=$(submit_barrier_slurm "stealth_barrier_gen" "afterok:$(join_job_ids "${SUBMITTED_JOB_IDS[@]}")") || exit 1
    echo "[PHASE] GEN submitted (${#GEN_JOBS[@]} jobs) -> barrier $gen_barrier"

    TIME_PER_TASK="$FLIPS_TIME"
    submit_job_pool_slurm FLIPS_JOBS "stealth_flips" "afterok:$gen_barrier" || exit 1
    flips_barrier=$(submit_barrier_slurm "stealth_barrier_flips" "afterok:$(join_job_ids "${SUBMITTED_JOB_IDS[@]}")") || exit 1
    echo "[PHASE] FLIPS submitted (${#FLIPS_JOBS[@]} jobs) -> barrier $flips_barrier"

    TIME_PER_TASK="$USER_TIME"
    submit_job_pool_slurm USER_JOBS "stealth_user" "afterok:$flips_barrier" || exit 1
    echo "[PHASE] USER submitted (${#USER_JOBS[@]} jobs)."
fi

echo "[DONE] campaign submitted; job ids in $LOG_DIR/jobids_*.txt"
echo "[NOTE] this module builds a second-order graph (create_graph=True) on the"
echo "[NOTE] expert step, with n_checkpoints_per_step=5 DISTINCT checkpoints held"
echo "[NOTE] simultaneously -- watch the first GEN job for OOM before the rest start."
