#!/bin/bash
###
# orchestrate_runs_trigger_joint_federated_multikrum_slurm.sh
#
# Slurm launcher for the federated_generate_labels_trigger_joint single-user vs federated
# Multi-Krum comparison generated by
# modules/federated_generate_labels_trigger_joint/gen_configs_federated_multikrum_compare.py --
# a SEPARATE campaign from every other orchestrate_runs_trigger_joint_*_slurm.sh script, so
# running it never interferes with the others.
#
# The attack (labels_syn + trigger delta) is generated ONCE per seed, at 1-poisoned/0-honest/
# mean -- NEVER regenerated for the federated branch (per this campaign's own design: see
# gen_configs_federated_multikrum_compare.py's docstring). From that single GEN cell, TWO
# downstream branches are submitted per (seed, budget):
#
#   [EXPERT]  train_expert                            (one per seed)
#        |
#   [GEN]     federated_generate_labels_trigger_joint  (one per seed, 1v0/mean)
#        |
#   [FLIPS]   federated_select_flips x2 per seed:
#               - single-user (1v0)
#               - federated   (3v7, nested under FED_TAG/)
#        |
#   [USER]    federated_train_user x2 per (seed, budget):
#               - single-user (1v0, mean)
#               - federated   (3v7, multikrum, track_poison_selection=true -- writes
#                              multikrum_poison_stats.json alongside caccs.npy/paccs.npy)
#
# Grid and directory layout below MUST match gen_configs_federated_multikrum_compare.py -- this
# script does NOT enumerate the axes itself, same by-hand-sync convention as every sibling
# script. Run `python -m modules.federated_generate_labels_trigger_joint.\
# gen_configs_federated_multikrum_compare --dry-run` to print the authoritative cell list if in
# doubt.
#
# Usage:
#   1. Generate the configs (from BASE_DIR):
#        python -m modules.federated_generate_labels_trigger_joint.gen_configs_federated_multikrum_compare
#   2. Submit the campaign:
#        SLURM_ACCOUNT=<account> ./orchestrate_runs_trigger_joint_federated_multikrum_slurm.sh
#        SLURM_ACCOUNT=<account> DRY_RUN=1 ./orchestrate_runs_trigger_joint_federated_multikrum_slurm.sh
###

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="${BASE_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"
export BASE_DIR
cd "$BASE_DIR"

# shellcheck source=slurm_lib.sh
source "$SCRIPT_DIR/slurm_lib.sh"

DRY_RUN="${DRY_RUN:-0}"

EXPERT_TIME="${EXPERT_TIME:-0-00:10:00}"
GEN_TIME="${GEN_TIME:-1-00:00:00}"
FLIPS_TIME="${FLIPS_TIME:-00:10:00}"
USER_TIME="${USER_TIME:-0-01:00:00}"

# ---------------------------------------------------------------------------
# Fixed axes -- MUST match gen_configs_federated_multikrum_compare.py's own constants.
# ---------------------------------------------------------------------------
MODEL_FLAG="${MODEL_FLAG:-r32p}"
DATASET="${DATASET:-cifar}"
AGG_METHOD="${AGG_METHOD:-mean}"
NUM_POISONED="${NUM_POISONED:-1}"
NUM_HONESTS="${NUM_HONESTS:-0}"
read -ra SEEDS   <<< "${SEEDS:-0}"
read -ra BUDGETS <<< "${BUDGETS:-500 2000}"

FED_NUM_POISONED="${FED_NUM_POISONED:-3}"
FED_NUM_HONESTS="${FED_NUM_HONESTS:-7}"
FED_AGG_METHOD="${FED_AGG_METHOD:-multikrum}"
FED_TAG="${FED_TAG:-federated_${FED_NUM_POISONED}vs${FED_NUM_HONESTS}_${FED_AGG_METHOD}}"

EXP_BASE_REL="${EXP_BASE_REL:-federated_experiments/threat_model_direct_trigger_joint_federated_multikrum}"

# ---------------------------------------------------------------------------
# Helpers -- mirror gen_configs_federated_multikrum_compare.py's cell_name()/directory layout.
# ---------------------------------------------------------------------------
MISSING=0

require_config() {
    local path="$1"
    if [ ! -f "experiments/$path/config.toml" ]; then
        echo "[CONFIG] missing: experiments/$path/config.toml" >&2
        MISSING=$((MISSING + 1))
    fi
}

cell_dir() {   # seed
    printf '%s/%s/%s/%svs%s/%s/seed%s' "$EXP_BASE_REL" "$MODEL_FLAG" "$DATASET" \
        "$NUM_POISONED" "$NUM_HONESTS" "$AGG_METHOD" "$1"
}

# ---------------------------------------------------------------------------
# Build the job lists. train_expert and the GEN (attack-generation) cell are per seed only,
# shared by both downstream branches. FLIPS/USER phases each bundle single-user and federated
# jobs together (they don't depend on each other, only on the phase before) -- 4 phases total,
# not 6.
# ---------------------------------------------------------------------------
EXPERT_JOBS=()
GEN_JOBS=()
FLIPS_JOBS=()
USER_JOBS=()

for seed in "${SEEDS[@]}"; do
  expert_cfg="$EXP_BASE_REL/train_expert/${MODEL_FLAG}_1xs/seed${seed}"
  require_config "$expert_cfg"
  EXPERT_JOBS+=("python run_experiment.py $expert_cfg|fedmk_expert_seed${seed}")

  cell="$(cell_dir "$seed")"
  gen_cfg="$cell/gen_labels_trigger_joint"
  require_config "$gen_cfg"
  GEN_JOBS+=("python run_experiment.py $gen_cfg|fedmk_gen_seed${seed}")

  flips_su_cfg="$cell/select_flips"
  flips_fed_cfg="$cell/$FED_TAG/select_flips"
  require_config "$flips_su_cfg"
  require_config "$flips_fed_cfg"
  FLIPS_JOBS+=("python run_experiment.py $flips_su_cfg|fedmk_flips_single_seed${seed}")
  FLIPS_JOBS+=("python run_experiment.py $flips_fed_cfg|fedmk_flips_fed_seed${seed}")

  for budget in "${BUDGETS[@]}"; do
    user_su_cfg="$cell/train_user_${budget}"
    user_fed_cfg="$cell/$FED_TAG/train_user_${budget}"
    require_config "$user_su_cfg"
    require_config "$user_fed_cfg"
    USER_JOBS+=("python run_experiment.py $user_su_cfg|fedmk_user_single_seed${seed}_${budget}")
    USER_JOBS+=("python run_experiment.py $user_fed_cfg|fedmk_user_fed_seed${seed}_${budget}")
  done
done

if [ "$MISSING" -gt 0 ]; then
    echo "[ABORT] $MISSING config(s) missing -- generate them first:" >&2
    echo "        python -m modules.federated_generate_labels_trigger_joint.gen_configs_federated_multikrum_compare" >&2
    exit 1
fi

echo "[PLAN] module=federated_generate_labels_trigger_joint_federated_multikrum exp_base=$EXP_BASE_REL"
echo "[PLAN] model=$MODEL_FLAG dataset=$DATASET attack_agg=$AGG_METHOD ${NUM_POISONED}vs${NUM_HONESTS}"
echo "[PLAN] federated branch: $FED_TAG (${FED_NUM_POISONED}vs${FED_NUM_HONESTS}, agg=$FED_AGG_METHOD)"
echo "[PLAN] seeds=${SEEDS[*]} budgets=${BUDGETS[*]}"
echo "[PLAN] cells=${#GEN_JOBS[@]} (=seeds), train_user jobs=${#USER_JOBS[@]} (=seeds x budgets x 2 branches)"
echo "[PLAN] partitions=${SLURM_PARTITIONS}"
echo "[PLAN] phases: EXPERT -> GEN -> FLIPS(single+federated) -> USER(single+federated)"

if [ "$DRY_RUN" = "1" ]; then
    echo "[DRY-RUN] nothing submitted."
    printf '[DRY-RUN] %s\n' "${EXPERT_JOBS[@]}"
    printf '[DRY-RUN] %s\n' "${GEN_JOBS[@]}"
    printf '[DRY-RUN] %s\n' "${FLIPS_JOBS[@]}"
    printf '[DRY-RUN] %s\n' "${USER_JOBS[@]}"
    exit 0
fi

preflight_slurm || exit 1

# ---------------------------------------------------------------------------
# Submit -- same job-pool/barrier pattern as every sibling script.
# ---------------------------------------------------------------------------
TIME_PER_TASK="$EXPERT_TIME"
submit_job_pool_slurm EXPERT_JOBS "fedmk_expert" "" || exit 1
expert_barrier=$(submit_barrier_slurm "fedmk_barrier_expert" "afterok:$(join_job_ids "${SUBMITTED_JOB_IDS[@]}")") || exit 1
echo "[PHASE] EXPERT submitted (${#EXPERT_JOBS[@]} jobs) -> barrier $expert_barrier"

TIME_PER_TASK="$GEN_TIME"
submit_job_pool_slurm GEN_JOBS "fedmk_gen" "afterok:$expert_barrier" || exit 1
gen_barrier=$(submit_barrier_slurm "fedmk_barrier_gen" "afterok:$(join_job_ids "${SUBMITTED_JOB_IDS[@]}")") || exit 1
echo "[PHASE] GEN submitted (${#GEN_JOBS[@]} jobs) -> barrier $gen_barrier"

TIME_PER_TASK="$FLIPS_TIME"
submit_job_pool_slurm FLIPS_JOBS "fedmk_flips" "afterok:$gen_barrier" || exit 1
flips_barrier=$(submit_barrier_slurm "fedmk_barrier_flips" "afterok:$(join_job_ids "${SUBMITTED_JOB_IDS[@]}")") || exit 1
echo "[PHASE] FLIPS submitted (${#FLIPS_JOBS[@]} jobs) -> barrier $flips_barrier"

TIME_PER_TASK="$USER_TIME"
submit_job_pool_slurm USER_JOBS "fedmk_user" "afterok:$flips_barrier" || exit 1
echo "[PHASE] USER submitted (${#USER_JOBS[@]} jobs)."

echo "[DONE] campaign submitted; job ids in $LOG_DIR/jobids_*.txt"
echo "[NOTE] the federated branch trains agg_method=multikrum with track_poison_selection=true;"
echo "[NOTE] each of its train_user jobs additionally writes multikrum_poison_stats.json"
echo "[NOTE] (see scripts/show_results/show_results.py's plot_multikrum_poison_selection)."
