#!/bin/bash
###
# orchestrate_runs_trigger_joint_paper_main_campaign_slurm.sh
#
# Slurm launcher for the paper's main-results campaign, generated by
# modules/federated_generate_labels_trigger_joint/gen_configs_paper_main_campaign.py: the three
# finalist stealth configs (baseline / eps_0p50_lpips_0p1 / eps_16_255, pulled from
# gen_configs_old_objective_port_stealth_sweep.py's own STEALTH_GRID) x {r32p, convnext_micro} x
# {cifar, svhn} x 10 seeds, each deployed against BOTH a single_user (1-poisoned/0-honest/mean)
# branch and a federated_3vs7 branch swept over {mean, krum, multikrum, median, trmean} x budgets
# {0, 150, 300, 500, 1000, 2000, 2500, 5000}.
#
# Chain, with afterok barriers between phases (same job-pool/barrier mechanics as the sibling
# campaign scripts):
#
#   [BOOTSTRAP] train_expert, one per (model_flag, dataset, seed) -- SHARED across the 3 tags
#               (regularization changes don't affect the clean bootstrap expert)
#        |
#   [GEN]       federated_generate_labels_trigger_joint, one per (model_flag, dataset, tag, seed)
#        |
#   [FLIPS]     federated_select_flips, one single_user + one federated_3vs7 per GEN cell
#        |
#   [USER]      federated_train_user (single_user: mean x budgets; federated_3vs7: 5 agg_methods
#               x budgets)
#
# Grid MUST match gen_configs_paper_main_campaign.py -- this script does NOT enumerate its grid
# itself. Run
#   python -m modules.federated_generate_labels_trigger_joint.gen_configs_paper_main_campaign --print-grid
#   python -m modules.federated_generate_labels_trigger_joint.gen_configs_paper_main_campaign --print-tags
# to print the authoritative cell list / finalist tag list if in doubt.
#
# SCALE WARNING: this is the full paper campaign, not a preliminary sweep -- 40 BOOTSTRAP + 120
# GEN + 240 FLIPS + 5760 USER = 6160 jobs total (one `sbatch` submission each, see slurm_lib.sh's
# own header comment -- no shared allocation). Check your cluster's per-user MaxSubmitJobs/
# MaxJobs limits before submitting the whole thing at once; use the MODEL_FLAGS/DATASETS/SEEDS/
# STEALTH_TAGS env overrides below to stage the campaign in smaller slices (e.g. one model or
# dataset at a time) if needed.
#
# Usage:
#   1. Generate the configs (from BASE_DIR):
#        python -m modules.federated_generate_labels_trigger_joint.gen_configs_paper_main_campaign
#   2. Submit the campaign (optionally sliced, see SCALE WARNING above):
#        SLURM_ACCOUNT=<account> ./orchestrate_runs_trigger_joint_paper_main_campaign_slurm.sh
#        SLURM_ACCOUNT=<account> DRY_RUN=1 ./orchestrate_runs_trigger_joint_paper_main_campaign_slurm.sh
#        SLURM_ACCOUNT=<account> MODEL_FLAGS="r32p" DATASETS="cifar" ./orchestrate_runs_trigger_joint_paper_main_campaign_slurm.sh
#
#   Re-run just the USER phase (e.g. after a train_user-only config fix), skipping
#   BOOTSTRAP/GEN/FLIPS entirely and reusing already-materialized flips/triggers on disk:
#        SLURM_ACCOUNT=<account> USER_ONLY=1 ./orchestrate_runs_trigger_joint_paper_main_campaign_slurm.sh
#
#   Re-run just GEN+FLIPS+USER, skipping BOOTSTRAP (reusing existing expert checkpoints):
#        SLURM_ACCOUNT=<account> BOOTSTRAP_SKIP=1 ./orchestrate_runs_trigger_joint_paper_main_campaign_slurm.sh
#
#   Submit only BOOTSTRAP -> GEN -> FLIPS, never USER -- when train_user is trained elsewhere
#   (e.g. orchestrate_student_machines/, off this cluster's job-count limit):
#        SLURM_ACCOUNT=<account> SKIP_USER=1 STEALTH_TAGS="eps_16_255" ./orchestrate_runs_trigger_joint_paper_main_campaign_slurm.sh
#
#   Resume a partially-completed campaign: GEN cells whose trigger .pt already exists on disk
#   (experiments/$EXP_BASE_REL/<model>/<dataset>/<tag>/seed<seed>/gen_labels_trigger_joint/
#   trigger/opt_trig_direct_joint_stripe_<model>_<dataset>_1vs0.pt) are skipped automatically --
#   only the missing GEN cells are (re)submitted. FLIPS branches whose select_flips output is
#   already fully materialized on disk (last budget's last worker's *_indices.npy present) are
#   skipped the same way -- only the missing single_user/federated FLIPS branches are
#   (re)submitted. FLIPS defaults to CPU-only (GPUS_PER_TASK=0, no --gres) since it never
#   touches a GPU -- set FLIPS_PARTITIONS to a CPU partition if the default SLURM_PARTITIONS is
#   GPU-only:
#        SLURM_ACCOUNT=<account> BOOTSTRAP_SKIP=1 FLIPS_PARTITIONS="<cpu_partition>" \
#            ./orchestrate_runs_trigger_joint_paper_main_campaign_slurm.sh
#   Force a GEN cell to redo even if its trigger already exists (e.g. after a code fix):
#        SLURM_ACCOUNT=<account> GEN_FORCE_ALL=1 ./orchestrate_runs_trigger_joint_paper_main_campaign_slurm.sh
###

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="${BASE_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"
export BASE_DIR
cd "$BASE_DIR"

# shellcheck source=slurm_lib.sh
source "$SCRIPT_DIR/slurm_lib.sh"

DRY_RUN="${DRY_RUN:-0}"
USER_ONLY="${USER_ONLY:-0}"
BOOTSTRAP_SKIP="${BOOTSTRAP_SKIP:-0}"
# Submit only BOOTSTRAP->GEN->FLIPS, never USER -- for when USER training is being done
# elsewhere (e.g. orchestrate_student_machines/, off a cluster job-count limit). Mutually
# exclusive with USER_ONLY in practice (nothing would be submitted if both are set).
SKIP_USER="${SKIP_USER:-0}"

BOOTSTRAP_TIME="${BOOTSTRAP_TIME:-0-06:00:00}"
GEN_TIME="${GEN_TIME:-1-00:00:00}"
FLIPS_TIME="${FLIPS_TIME:-00:10:00}"
USER_TIME="${USER_TIME:-0-01:00:00}"

# GEN cells whose trigger .pt is already on disk are skipped by default (see "Resume a
# partially-completed campaign" in the header Usage section). Set GEN_FORCE_ALL=1 to
# resubmit every GEN cell regardless of what's already on disk.
GEN_FORCE_ALL="${GEN_FORCE_ALL:-0}"

# FLIPS (federated_select_flips) never touches a GPU -- it only reads labels.npy/true.npy off
# disk and writes flip-index .npy files. Defaults to a CPU-only submission (no --gres at all,
# see slurm_lib.sh's submit_job_slurm) on the SAME partitions as the rest of the campaign;
# override FLIPS_PARTITIONS to point it at an actual CPU partition if SLURM_PARTITIONS is
# GPU-only on this cluster. Set FLIPS_GPUS_PER_TASK=1 to go back to the old GPU-slot behavior.
FLIPS_GPUS_PER_TASK="${FLIPS_GPUS_PER_TASK:-0}"
FLIPS_PARTITIONS="${FLIPS_PARTITIONS:-$SLURM_PARTITIONS}"
FLIPS_MEM="${FLIPS_MEM:-4G}"

# ---------------------------------------------------------------------------
# Fixed axes -- MUST match gen_configs_paper_main_campaign.py's own constants. Every one of
# these is env-overridable so the campaign can be staged in smaller slices (see SCALE WARNING
# in the header comment above) -- e.g. MODEL_FLAGS="r32p" to submit only that model's cells.
# ---------------------------------------------------------------------------
read -ra MODEL_FLAGS <<< "${MODEL_FLAGS:-r32p convnext_micro}"
read -ra DATASETS <<< "${DATASETS:-cifar svhn}"
read -ra SEEDS <<< "${SEEDS:-0 1 2 3 4 5 6 7 8 9}"
# STEALTH_GRID's own three finalist tags (module docstring) -- keep in sync by hand; verify
# with --print-tags if in doubt.
read -ra STEALTH_TAGS <<< "${STEALTH_TAGS:-baseline eps_0p50_lpips_0p1 eps_16_255}"
read -ra DEPLOY_BUDGETS <<< "${DEPLOY_BUDGETS:-0 150 300 500 1000 2000 2500 5000}"
DEPLOY_SINGLE_USER_AGG="${DEPLOY_SINGLE_USER_AGG:-mean}"
read -ra DEPLOY_AGG_METHODS_FEDERATED <<< "${DEPLOY_AGG_METHODS_FEDERATED:-mean krum multikrum median trmean}"
FEDERATED_TAG="${FEDERATED_TAG:-federated_3vs7}"

EXP_BASE_REL="${EXP_BASE_REL:-federated_experiments/threat_model_direct_trigger_joint_paper_main_campaign}"

# Distinguishes this invocation's phase names/log files from any other (e.g. when the campaign
# is staged across several sequential calls with different MODEL_FLAGS/DATASETS slices, see the
# header's Usage section) -- otherwise every slice would submit under the SAME phase name
# ("paper_gen", "paper_user", ...), truncating (see slurm_lib.sh's submit_job_pool_slurm:
# `: > "$id_file"`) the PREVIOUS slice's $LOG_DIR/jobids_<phase>.txt on every new invocation.
# Purely a logging/job-naming concern -- submit_job_pool_slurm/submit_barrier_slurm build every
# afterok dependency from the in-memory SUBMITTED_JOB_IDS array, never by re-reading these
# files, so a collision here does NOT corrupt any invocation's own barrier chain. Override
# explicitly (RUN_TAG=foo) if the default (models + datasets, slash-joined) collides anyway.
RUN_TAG="${RUN_TAG:-$(IFS=-; echo "${MODEL_FLAGS[*]}")_$(IFS=-; echo "${DATASETS[*]}")}"

# ---------------------------------------------------------------------------
# Config / prerequisite presence check.
# ---------------------------------------------------------------------------
MISSING=0

require_config() {
    local path="$1"
    if [ ! -f "experiments/$path/config.toml" ]; then
        echo "[CONFIG] missing: experiments/$path/config.toml" >&2
        MISSING=$((MISSING + 1))
    fi
}

BOOTSTRAP_JOBS=()
for model in "${MODEL_FLAGS[@]}"; do
  for dataset in "${DATASETS[@]}"; do
    for seed in "${SEEDS[@]}"; do
      bootstrap_cfg="$EXP_BASE_REL/train_expert/${model}_${dataset}_1xs/seed${seed}"
      require_config "$bootstrap_cfg"
      BOOTSTRAP_JOBS+=("python run_experiment.py $bootstrap_cfg|paper_bootstrap_${model}_${dataset}_seed${seed}")
    done
  done
done

# GEN's own last write (run_module.py's run(): torch.save(delta, ...) AFTER labels.npy/true.npy/
# losses.npy) -- its presence means the cell's GEN already completed successfully. Path/name
# MUST match gen_configs_old_objective_port.GEN_INIT ("stripe") and
# gen_configs_paper_main_campaign.py's GEN_NUM_POISONED=1/GEN_NUM_HONESTS=0 ("1vs0"); verify
# with --print-grid if this drifts.
GEN_INIT_TAG="stripe"
gen_labels_done() {
    local model="$1" dataset="$2" tag="$3" seed="$4"
    local trig="experiments/$EXP_BASE_REL/$model/$dataset/$tag/seed${seed}/gen_labels_trigger_joint/trigger/opt_trig_direct_joint_${GEN_INIT_TAG}_${model}_${dataset}_1vs0.pt"
    [ -f "$trig" ]
}

# federated_select_flips's own last write (run_module.py's run(): for each budget IN ORDER,
# np.save idx_flipped/idx_clean THEN, per worker (0..num_workers-1) IN ORDER, worker{w}/
# {budget}_labels.npy THEN worker{w}/{budget}_indices.npy) -- the LAST budget in DEPLOY_BUDGETS'
# LAST worker's indices.npy is therefore the last file select_flips ever writes; its presence
# means that flips_dir's select_flips run already completed. num_workers = deploy_num_honests +
# deploy_num_poisoned MUST match gen_configs_paper_main_campaign.py's own DEPLOY_SINGLE_USER_*
# (0+1=1) / DEPLOY_FEDERATED_* (7+3=10) constants; verify with --print-grid if this drifts.
FLIPS_LAST_BUDGET="${DEPLOY_BUDGETS[-1]}"
FLIPS_SINGLE_USER_WORKERS=1
FLIPS_FEDERATED_WORKERS=10
flips_done() {
    local flips_dir="$1" num_workers="$2"
    local last_worker=$((num_workers - 1))
    [ -f "experiments/$flips_dir/worker${last_worker}/${FLIPS_LAST_BUDGET}_indices.npy" ]
}

GEN_JOBS=()
GEN_SKIPPED=0
FLIPS_JOBS=()
FLIPS_SKIPPED=0
for model in "${MODEL_FLAGS[@]}"; do
  for dataset in "${DATASETS[@]}"; do
    for tag in "${STEALTH_TAGS[@]}"; do
      for seed in "${SEEDS[@]}"; do
        cell="$EXP_BASE_REL/$model/$dataset/$tag/seed${seed}"
        gen_cfg="$cell/gen_labels_trigger_joint"
        flips_cfg="$cell/select_flips"
        fed_flips_cfg="$cell/$FEDERATED_TAG/select_flips"

        # FLIPS: skip a branch whose select_flips output is already fully materialized on
        # disk (see flips_done above), same idea as GEN's skip-if-done check below.
        if flips_done "$flips_cfg" "$FLIPS_SINGLE_USER_WORKERS"; then
            FLIPS_SKIPPED=$((FLIPS_SKIPPED + 1))
        else
            require_config "$flips_cfg"
            FLIPS_JOBS+=("python run_experiment.py $flips_cfg|paper_flips_${model}_${dataset}_${tag}_seed${seed}")
        fi
        if flips_done "$fed_flips_cfg" "$FLIPS_FEDERATED_WORKERS"; then
            FLIPS_SKIPPED=$((FLIPS_SKIPPED + 1))
        else
            require_config "$fed_flips_cfg"
            FLIPS_JOBS+=("python run_experiment.py $fed_flips_cfg|paper_flips_fed_${model}_${dataset}_${tag}_seed${seed}")
        fi

        if [ "$GEN_FORCE_ALL" != "1" ] && gen_labels_done "$model" "$dataset" "$tag" "$seed"; then
            GEN_SKIPPED=$((GEN_SKIPPED + 1))
            continue
        fi
        require_config "$gen_cfg"
        GEN_JOBS+=("python run_experiment.py $gen_cfg|paper_gen_${model}_${dataset}_${tag}_seed${seed}")
      done
    done
  done
done

USER_JOBS=()
for model in "${MODEL_FLAGS[@]}"; do
  for dataset in "${DATASETS[@]}"; do
    for tag in "${STEALTH_TAGS[@]}"; do
      for seed in "${SEEDS[@]}"; do
        cell="$EXP_BASE_REL/$model/$dataset/$tag/seed${seed}"
        for budget in "${DEPLOY_BUDGETS[@]}"; do
          user_cfg="$cell/$DEPLOY_SINGLE_USER_AGG/train_user_${budget}"
          require_config "$user_cfg"
          USER_JOBS+=("python run_experiment.py $user_cfg|paper_user_${model}_${dataset}_${tag}_seed${seed}_su_${budget}")
        done
        for agg_method in "${DEPLOY_AGG_METHODS_FEDERATED[@]}"; do
          for budget in "${DEPLOY_BUDGETS[@]}"; do
            user_cfg="$cell/$FEDERATED_TAG/$agg_method/train_user_${budget}"
            require_config "$user_cfg"
            USER_JOBS+=("python run_experiment.py $user_cfg|paper_user_${model}_${dataset}_${tag}_seed${seed}_${agg_method}_${budget}")
          done
        done
      done
    done
  done
done

if [ "$MISSING" -gt 0 ]; then
    echo "[ABORT] $MISSING config(s) missing -- generate them first:" >&2
    echo "        python -m modules.federated_generate_labels_trigger_joint.gen_configs_paper_main_campaign" >&2
    exit 1
fi

echo "[PLAN] campaign=paper_main_campaign exp_base=$EXP_BASE_REL run_tag=$RUN_TAG"
echo "[PLAN] models=${MODEL_FLAGS[*]} datasets=${DATASETS[*]} seeds=${#SEEDS[@]} (${SEEDS[*]}) tags=${STEALTH_TAGS[*]}"
echo "[PLAN] deployment: single_user agg=$DEPLOY_SINGLE_USER_AGG, federated($FEDERATED_TAG) agg_methods=${DEPLOY_AGG_METHODS_FEDERATED[*]}, budgets=${DEPLOY_BUDGETS[*]}"
echo "[PLAN] bootstrap cells=${#BOOTSTRAP_JOBS[@]} gen cells=${#GEN_JOBS[@]} (skipped, already done=$GEN_SKIPPED) flips cells=${#FLIPS_JOBS[@]} (skipped, already done=$FLIPS_SKIPPED) user cells=${#USER_JOBS[@]}"
echo "[PLAN] partitions=${SLURM_PARTITIONS}; flips partitions=${FLIPS_PARTITIONS} gpus_per_task=${FLIPS_GPUS_PER_TASK} (0 = CPU-only, no --gres)"
if [ "$USER_ONLY" = "1" ]; then
    echo "[PLAN] phases: USER only (USER_ONLY=1 -- reusing existing BOOTSTRAP/GEN/FLIPS outputs on disk)"
elif [ "$SKIP_USER" = "1" ]; then
    if [ "$BOOTSTRAP_SKIP" = "1" ]; then
        echo "[PLAN] phases: GEN -> FLIPS only (SKIP_USER=1, BOOTSTRAP_SKIP=1 -- USER trained elsewhere)"
    else
        echo "[PLAN] phases: BOOTSTRAP -> GEN -> FLIPS only (SKIP_USER=1 -- USER trained elsewhere, e.g. orchestrate_student_machines/)"
    fi
elif [ "$BOOTSTRAP_SKIP" = "1" ]; then
    echo "[PLAN] phases: GEN -> FLIPS -> USER (BOOTSTRAP_SKIP=1 -- reusing existing bootstrap checkpoints)"
else
    echo "[PLAN] phases: BOOTSTRAP -> GEN -> FLIPS -> USER"
fi

if [ "$DRY_RUN" = "1" ]; then
    echo "[DRY-RUN] nothing submitted."
    if [ "$USER_ONLY" != "1" ]; then
        if [ "$BOOTSTRAP_SKIP" != "1" ]; then
            printf '[DRY-RUN] %s\n' "${BOOTSTRAP_JOBS[@]}"
        fi
        printf '[DRY-RUN] %s\n' "${GEN_JOBS[@]}"
        printf '[DRY-RUN] %s\n' "${FLIPS_JOBS[@]}"
    fi
    if [ "$SKIP_USER" != "1" ]; then
        printf '[DRY-RUN] %s\n' "${USER_JOBS[@]}"
    fi
    exit 0
fi

preflight_slurm || exit 1

# preflight_slurm above only trial-probes SLURM_PARTITIONS with the GPU resource shape
# (--gres=gpu:$GPUS_PER_TASK); when FLIPS_PARTITIONS points at a different (e.g. CPU-only)
# partition, probe THAT partition with the CPU-only shape FLIPS jobs will actually request, so
# a bad partition name / unusable account-partition pair is caught now instead of after 240
# FLIPS submissions.
if [ "$FLIPS_PARTITIONS" != "$SLURM_PARTITIONS" ]; then
    for _flips_partition in $FLIPS_PARTITIONS; do
        if ! sinfo -h -p "$_flips_partition" -o "%P" 2>/dev/null | grep -q .; then
            echo "[PREFLIGHT] FLIPS_PARTITIONS partition '$_flips_partition' unknown or unreachable" >&2
            exit 1
        fi
        _flips_probe_gres=()
        [ "$FLIPS_GPUS_PER_TASK" != "0" ] && _flips_probe_gres=(--gres="gpu:$FLIPS_GPUS_PER_TASK")
        if ! sbatch --kill-on-invalid-dep=yes --test-only \
                --account="$SLURM_ACCOUNT" --partition="$_flips_partition" \
                "${_flips_probe_gres[@]}" --cpus-per-task="$CPUS_PER_TASK" \
                --mem="$FLIPS_MEM" --time=00:01:00 --wrap=true >/dev/null 2>&1; then
            echo "[PREFLIGHT] a trial submission to FLIPS_PARTITIONS partition '$_flips_partition' was rejected by Slurm" >&2
            exit 1
        fi
    done
    unset _flips_partition _flips_probe_gres
fi

# ---------------------------------------------------------------------------
# Submit -- same job-pool/barrier pattern as the sibling campaign scripts.
# ---------------------------------------------------------------------------
if [ "$USER_ONLY" = "1" ]; then
    TIME_PER_TASK="$USER_TIME"
    submit_job_pool_slurm USER_JOBS "paper_user_${RUN_TAG}" || exit 1
    echo "[PHASE] USER submitted (${#USER_JOBS[@]} jobs), no dependency (USER_ONLY=1)."
else
    gen_dep=""
    if [ "$BOOTSTRAP_SKIP" != "1" ]; then
        TIME_PER_TASK="$BOOTSTRAP_TIME"
        submit_job_pool_slurm BOOTSTRAP_JOBS "paper_bootstrap_${RUN_TAG}" || exit 1
        bootstrap_barrier=$(submit_barrier_slurm "paper_barrier_bootstrap_${RUN_TAG}" "afterok:$(join_job_ids "${SUBMITTED_JOB_IDS[@]}")") || exit 1
        echo "[PHASE] BOOTSTRAP submitted (${#BOOTSTRAP_JOBS[@]} jobs) -> barrier $bootstrap_barrier"
        gen_dep="afterok:$bootstrap_barrier"
    else
        echo "[PHASE] BOOTSTRAP skipped (BOOTSTRAP_SKIP=1)."
    fi

    flips_dep="$gen_dep"
    if [ ${#GEN_JOBS[@]} -gt 0 ]; then
        TIME_PER_TASK="$GEN_TIME"
        submit_job_pool_slurm GEN_JOBS "paper_gen_${RUN_TAG}" "$gen_dep" || exit 1
        gen_barrier=$(submit_barrier_slurm "paper_barrier_gen_${RUN_TAG}" "afterok:$(join_job_ids "${SUBMITTED_JOB_IDS[@]}")") || exit 1
        echo "[PHASE] GEN submitted (${#GEN_JOBS[@]} jobs, $GEN_SKIPPED already done -- skipped) -> barrier $gen_barrier"
        flips_dep="afterok:$gen_barrier"
    else
        echo "[PHASE] GEN skipped entirely -- all $GEN_SKIPPED cells already have a trigger on disk."
    fi

    # FLIPS never touches a GPU -- submitted CPU-only (FLIPS_GPUS_PER_TASK=0 by default, see
    # header Usage section) on FLIPS_PARTITIONS, independently of the GPU resources/partitions
    # the rest of the campaign uses. Branches already resubmitted regardless of GEN_SKIPPED are
    # the ones NOT already done on disk -- see flips_done/FLIPS_SKIPPED above.
    user_dep="$flips_dep"
    if [ ${#FLIPS_JOBS[@]} -gt 0 ]; then
        TIME_PER_TASK="$FLIPS_TIME"
        _saved_gpus_per_task="$GPUS_PER_TASK"
        _saved_mem_per_task="$MEM_PER_TASK"
        _saved_slurm_partitions="$SLURM_PARTITIONS"
        GPUS_PER_TASK="$FLIPS_GPUS_PER_TASK"
        MEM_PER_TASK="$FLIPS_MEM"
        SLURM_PARTITIONS="$FLIPS_PARTITIONS"
        submit_job_pool_slurm FLIPS_JOBS "paper_flips_${RUN_TAG}" "$flips_dep" || exit 1
        GPUS_PER_TASK="$_saved_gpus_per_task"
        MEM_PER_TASK="$_saved_mem_per_task"
        SLURM_PARTITIONS="$_saved_slurm_partitions"
        flips_barrier=$(submit_barrier_slurm "paper_barrier_flips_${RUN_TAG}" "afterok:$(join_job_ids "${SUBMITTED_JOB_IDS[@]}")") || exit 1
        echo "[PHASE] FLIPS submitted (${#FLIPS_JOBS[@]} jobs, $FLIPS_SKIPPED already done -- skipped, gpus_per_task=$FLIPS_GPUS_PER_TASK, partitions=$FLIPS_PARTITIONS) -> barrier $flips_barrier"
        user_dep="afterok:$flips_barrier"
    else
        echo "[PHASE] FLIPS skipped entirely -- all $FLIPS_SKIPPED branches already have flips on disk."
    fi

    if [ "$SKIP_USER" != "1" ]; then
        TIME_PER_TASK="$USER_TIME"
        submit_job_pool_slurm USER_JOBS "paper_user_${RUN_TAG}" "$user_dep" || exit 1
        echo "[PHASE] USER submitted (${#USER_JOBS[@]} jobs)."
    else
        echo "[PHASE] USER skipped (SKIP_USER=1 -- train it elsewhere, e.g. orchestrate_student_machines/)."
    fi
fi

echo "[DONE] campaign submitted (RUN_TAG=$RUN_TAG); job ids in $LOG_DIR/jobids_*_${RUN_TAG}.txt"
echo "[NOTE] this module builds a second-order graph (create_graph=True) on the"
echo "[NOTE] expert step, with n_checkpoints_per_step=5 DISTINCT checkpoints held"
echo "[NOTE] simultaneously -- watch the first GEN job for OOM before the rest start."
