#!/bin/bash
###
# orchestrate_runs_trigger_joint_expert_retrain_compare_slurm.sh
#
# Slurm launcher for the federated_generate_labels_trigger_joint live-expert-retraining
# comparison (expert_retrain_interval=0 [disabled, frozen trajectory] vs 1 [retrain every outer
# iteration], see run_module.py's run() docstring, "Live expert retraining") generated by
# modules/federated_generate_labels_trigger_joint/gen_configs_expert_retrain_compare.py -- a
# SEPARATE campaign from orchestrate_runs_trigger_joint_slurm.sh (the main campaign),
# orchestrate_runs_trigger_joint_sweep_slurm.sh (the OFAT hyperparameter sweep),
# orchestrate_runs_trigger_joint_gradmatch_metric_slurm.sh, and
# orchestrate_runs_trigger_joint_init_compare_slurm.sh, so running one never interferes with the
# others.
#
# Chain, one Slurm job per cell, with afterok barriers between phases -- same job-pool/barrier
# mechanics as the sibling scripts above:
#
#   [EXPERT]  train_expert                           (one per seed, shared across both interval
#        |                                             cells of that seed -- expert_retrain_
#        |                                             interval doesn't affect the INITIAL
#        |                                             train_expert step at all)
#   [GEN]     federated_generate_labels_trigger_joint (one per expert_retrain_interval value)
#        |
#   [FLIPS]   federated_select_flips
#        |
#   [USER]    federated_train_user                    (full budget sweep per cell, see
#                                                        gen_configs_expert_retrain_compare.py's
#                                                        BUDGETS)
#
# Grid and directory layout below MUST match gen_configs_expert_retrain_compare.py -- this
# script does NOT enumerate the axes itself, same by-hand-sync convention as the sibling
# scripts. Run `python -m modules.federated_generate_labels_trigger_joint.
# gen_configs_expert_retrain_compare --dry-run` to print the authoritative cell list if in doubt.
#
# Usage:
#   1. Generate the configs (from BASE_DIR):
#        python -m modules.federated_generate_labels_trigger_joint.gen_configs_expert_retrain_compare
#   2. Submit the campaign:
#        SLURM_ACCOUNT=<account> ./orchestrate_runs_trigger_joint_expert_retrain_compare_slurm.sh
#        SLURM_ACCOUNT=<account> DRY_RUN=1 ./orchestrate_runs_trigger_joint_expert_retrain_compare_slurm.sh
#
# NOTE (GEN_TIME): interval=1 retrains a fresh expert (EPOCHS_EXPERT epochs) every single outer
# iteration -- substantially more wall-clock than interval=0's frozen trajectory. GEN_TIME below
# is capped at 1 day (the cluster's max requestable walltime -- see slurm_lib.sh's own
# MaxTime=1-00:00:00 note) rather than sized generously for interval=1: if the interval=1 job
# doesn't finish within it, Slurm kills it at the wall-clock limit (afterok is never satisfied,
# so nothing downstream runs) -- there's no larger budget available to ask for instead, so this
# is the ceiling, not a comfortable margin.
###

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="${BASE_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"
export BASE_DIR
cd "$BASE_DIR"

# shellcheck source=slurm_lib.sh
source "$SCRIPT_DIR/slurm_lib.sh"

DRY_RUN="${DRY_RUN:-0}"

EXPERT_TIME="${EXPERT_TIME:-0-00:10:00}"
GEN_TIME="${GEN_TIME:-1-00:00:00}"
FLIPS_TIME="${FLIPS_TIME:-00:10:00}"
USER_TIME="${USER_TIME:-0-01:00:00}"

# ---------------------------------------------------------------------------
# Fixed axes -- MUST match gen_configs_expert_retrain_compare.py's own constants.
# ---------------------------------------------------------------------------
MODEL_FLAG="${MODEL_FLAG:-r32p}"
DATASET="${DATASET:-cifar}"
AGG_METHOD="${AGG_METHOD:-mean}"
NUM_POISONED="${NUM_POISONED:-1}"
NUM_HONESTS="${NUM_HONESTS:-0}"
read -ra SEEDS   <<< "${SEEDS:-0}"
read -ra BUDGETS <<< "${BUDGETS:-150 300 500 1000 2000 2500 5000}"

# The axis this comparison varies -- see gen_configs_expert_retrain_compare.py's
# EXPERT_RETRAIN_INTERVALS.
read -ra INTERVALS <<< "${INTERVALS:-0 1}"

EXP_BASE_REL="${EXP_BASE_REL:-federated_experiments/threat_model_direct_trigger_joint_expert_retrain_compare}"

# ---------------------------------------------------------------------------
# Helpers -- mirror gen_configs_expert_retrain_compare.py's cell_name()/directory layout
# exactly.
# ---------------------------------------------------------------------------
MISSING=0

require_config() {
    local path="$1"
    if [ ! -f "experiments/$path/config.toml" ]; then
        echo "[CONFIG] missing: experiments/$path/config.toml" >&2
        MISSING=$((MISSING + 1))
    fi
}

cell_dir() {   # interval seed
    printf '%s/%s/%s/%svs%s/%s/retrain_interval_%s/seed%s' "$EXP_BASE_REL" "$MODEL_FLAG" "$DATASET" \
        "$NUM_POISONED" "$NUM_HONESTS" "$AGG_METHOD" "$1" "$2"
}

# ---------------------------------------------------------------------------
# Build the job lists (seed -> interval -> budget), following
# gen_configs_expert_retrain_compare.py's own nesting and directory layout. train_expert is per
# seed only (shared across both interval cells of that seed), so it is deduplicated instead of
# resubmitted per cell.
# ---------------------------------------------------------------------------
EXPERT_JOBS=()
GEN_JOBS=()
FLIPS_JOBS=()
USER_JOBS=()

for seed in "${SEEDS[@]}"; do
  expert_cfg="$EXP_BASE_REL/train_expert/${MODEL_FLAG}_1xs/seed${seed}"
  require_config "$expert_cfg"
  EXPERT_JOBS+=("python run_experiment.py $expert_cfg|erc_expert_seed${seed}")

  for interval in "${INTERVALS[@]}"; do
    cell="$(cell_dir "$interval" "$seed")"
    job_tag="seed${seed}_interval${interval}"

    gen_cfg="$cell/gen_labels_trigger_joint"
    flips_cfg="$cell/select_flips"

    require_config "$gen_cfg"
    require_config "$flips_cfg"

    GEN_JOBS+=("python run_experiment.py $gen_cfg|erc_gen_${job_tag}")
    FLIPS_JOBS+=("python run_experiment.py $flips_cfg|erc_flips_${job_tag}")

    for budget in "${BUDGETS[@]}"; do
      user_cfg="$cell/train_user_${budget}"
      require_config "$user_cfg"
      USER_JOBS+=("python run_experiment.py $user_cfg|erc_user_${job_tag}_${budget}")
    done
  done
done

if [ "$MISSING" -gt 0 ]; then
    echo "[ABORT] $MISSING config(s) missing -- generate them first:" >&2
    echo "        python -m modules.federated_generate_labels_trigger_joint.gen_configs_expert_retrain_compare" >&2
    exit 1
fi

echo "[PLAN] module=federated_generate_labels_trigger_joint_expert_retrain_compare exp_base=$EXP_BASE_REL"
echo "[PLAN] model=$MODEL_FLAG dataset=$DATASET agg=$AGG_METHOD ${NUM_POISONED}vs${NUM_HONESTS}"
echo "[PLAN] seeds=${SEEDS[*]} intervals=${INTERVALS[*]} budgets=${BUDGETS[*]}"
echo "[PLAN] cells=${#GEN_JOBS[@]} (=seeds x intervals), train_user jobs=${#USER_JOBS[@]}"
echo "[PLAN] partitions=${SLURM_PARTITIONS}"
echo "[PLAN] phases: EXPERT -> GEN -> FLIPS -> USER"
echo "[PLAN] NOTE: interval=1 retrains a fresh expert every outer iteration -- expect the GEN"
echo "[PLAN] phase's interval=1 jobs to take substantially longer than interval=0's, and"
echo "[PLAN] possibly hit GEN_TIME=$GEN_TIME (the 1-day cap) if N_ITERATIONS is large -- watch"
echo "[PLAN] the first interval=1 job; lower N_ITERATIONS/EXPERT_RETRAIN_EPOCHS in"
echo "[PLAN] gen_configs_expert_retrain_compare.py if it times out instead."

if [ "$DRY_RUN" = "1" ]; then
    echo "[DRY-RUN] nothing submitted."
    printf '[DRY-RUN] %s\n' "${EXPERT_JOBS[@]}"
    printf '[DRY-RUN] %s\n' "${GEN_JOBS[@]}"
    printf '[DRY-RUN] %s\n' "${FLIPS_JOBS[@]}"
    printf '[DRY-RUN] %s\n' "${USER_JOBS[@]}"
    exit 0
fi

preflight_slurm || exit 1

# ---------------------------------------------------------------------------
# Submit -- same job-pool/barrier pattern as the sibling scripts.
# ---------------------------------------------------------------------------
TIME_PER_TASK="$EXPERT_TIME"
submit_job_pool_slurm EXPERT_JOBS "erc_expert" "" || exit 1
expert_barrier=$(submit_barrier_slurm "erc_barrier_expert" "afterok:$(join_job_ids "${SUBMITTED_JOB_IDS[@]}")") || exit 1
echo "[PHASE] EXPERT submitted (${#EXPERT_JOBS[@]} jobs) -> barrier $expert_barrier"

TIME_PER_TASK="$GEN_TIME"
submit_job_pool_slurm GEN_JOBS "erc_gen" "afterok:$expert_barrier" || exit 1
gen_barrier=$(submit_barrier_slurm "erc_barrier_gen" "afterok:$(join_job_ids "${SUBMITTED_JOB_IDS[@]}")") || exit 1
echo "[PHASE] GEN submitted (${#GEN_JOBS[@]} jobs) -> barrier $gen_barrier"

TIME_PER_TASK="$FLIPS_TIME"
submit_job_pool_slurm FLIPS_JOBS "erc_flips" "afterok:$gen_barrier" || exit 1
flips_barrier=$(submit_barrier_slurm "erc_barrier_flips" "afterok:$(join_job_ids "${SUBMITTED_JOB_IDS[@]}")") || exit 1
echo "[PHASE] FLIPS submitted (${#FLIPS_JOBS[@]} jobs) -> barrier $flips_barrier"

TIME_PER_TASK="$USER_TIME"
submit_job_pool_slurm USER_JOBS "erc_user" "afterok:$flips_barrier" || exit 1
echo "[PHASE] USER submitted (${#USER_JOBS[@]} jobs)."

echo "[DONE] campaign submitted; job ids in $LOG_DIR/jobids_*.txt"
echo "[NOTE] this module builds a second-order graph (create_graph=True) on the"
echo "[NOTE] expert step: memory is ~2.6x the non-differentiable variant on a CPU"
echo "[NOTE] proxy measurement. Watch the first GEN job for OOM before the rest start."
