"""
Picks the best hyperparameter/regularization config out of the federated_generate_labels_
trigger_joint sweep generated by modules/federated_generate_labels_trigger_joint/
gen_configs_sweep.py (30 cells: 1 baseline + one-at-a-time variants over lr_delta, lambda_bd,
n_iterations, epsilon, gamma_stealth, lambda_delta, trigger_constraint, align_kappa,
lambda_align, lambda_mag, delta_min_frac -- see that file's own docstring).

Reads every cell's train_user_<budget>/{caccs,paccs}.npy (CTA/ASR, same convention as
show_results.py), then reports, in order:

  1. The full cell ranking, sorted by ASR (attack success rate) descending -- the primary
     metric for this proof-of-concept sweep (see the session's own framing: showing what the
     attack CAN achieve, not a stealth-optimized one).
  2. A per-axis breakdown: for each swept axis, every tested value's (CTA, ASR) next to
     baseline's, so you can see which individual knobs actually helped and by how much.
  3. A "combined" candidate config: baseline with, for each axis, the best-performing tested
     value substituted in (only where it beats baseline's ASR) -- a suggestion for a follow-up
     single-cell run, NOT a value read off an actual sweep cell (one-at-a-time sweeps don't
     test axis interactions, so this combination has never actually been run -- see the CAVEAT
     printed with it).

Usage: python analyze_trigger_joint_sweep.py [--generate-combined]
  --generate-combined also writes the "combined" candidate as a new sweep cell (tag
  "combined_best") via gen_configs_sweep.generate_cell, ready to add to
  orchestrate_runs_trigger_joint_sweep_slurm.sh's CELL_TAGS for a confirmation run.
"""
import argparse

import numpy as np

from modules.federated_generate_labels_trigger_joint.gen_configs_sweep import (
    BASELINE,
    BUDGETS,
    DATASET,
    EXP_BASE,
    MODEL_FLAG,
    NUM_HONESTS,
    NUM_POISONED,
    SEEDS,
    SWEEP_AXES,
    build_cells,
    generate_cell,
)


def get_final_value(npy_path):
    try:
        if not npy_path.exists() or npy_path.stat().st_size == 0:
            return np.nan
        data = np.load(npy_path, allow_pickle=True)
        if data.size == 0:
            return np.nan
        return float(data[-1][0]) if data.ndim > 1 else float(data[-1])
    except Exception:
        return np.nan


def cell_dir_for(tag, seed):
    return EXP_BASE / f"{MODEL_FLAG}/{DATASET}/{NUM_POISONED}vs{NUM_HONESTS}/seed{seed}/{tag}"


def load_results():
    """{tag: {"overrides": dict, "cta": mean over seeds, "asr": mean over seeds,
    "per_seed": {seed: (cta, asr)}}}"""
    results = {}
    for tag, overrides in build_cells():
        per_seed = {}
        for seed in SEEDS:
            cell_dir = cell_dir_for(tag, seed)
            budget = BUDGETS[0]
            train_user_dir = cell_dir / f"train_user_{budget}"
            cta = get_final_value(train_user_dir / "caccs.npy")
            asr = get_final_value(train_user_dir / "paccs.npy")
            per_seed[seed] = (cta, asr)
        ctas = [v[0] for v in per_seed.values() if not np.isnan(v[0])]
        asrs = [v[1] for v in per_seed.values() if not np.isnan(v[1])]
        results[tag] = {
            "overrides": overrides,
            "cta": float(np.mean(ctas)) if ctas else np.nan,
            "asr": float(np.mean(asrs)) if asrs else np.nan,
            "per_seed": per_seed,
        }
    return results


def fmt(x):
    return "pending" if (x is None or (isinstance(x, float) and np.isnan(x))) else f"{x:.4f}"


def sort_key(item):
    _, r = item
    asr = r["asr"]
    cta = r["cta"]
    asr_key = -1.0 if np.isnan(asr) else asr
    cta_key = -1.0 if np.isnan(cta) else cta
    return (-asr_key, -cta_key)


def print_ranking(results):
    print(f"\n=== Full ranking, {len(results)} cells, sorted by ASR desc ===")
    print(f"{'tag':<28} {'override':<28} {'CTA':>8} {'ASR':>8}")
    for tag, r in sorted(results.items(), key=sort_key):
        override_str = ", ".join(f"{k}={v}" for k, v in r["overrides"].items()) or "(baseline)"
        print(f"{tag:<28} {override_str:<28} {fmt(r['cta']):>8} {fmt(r['asr']):>8}")


def print_axis_breakdown(results):
    print("\n=== Per-axis breakdown (vs baseline) ===")
    baseline = results["baseline"]
    best_per_axis = {}
    for axis in SWEEP_AXES:
        rows = [(BASELINE[axis], baseline["cta"], baseline["asr"], "baseline")]
        for tag, r in results.items():
            if list(r["overrides"].keys()) == [axis]:
                rows.append((r["overrides"][axis], r["cta"], r["asr"], tag))
        rows.sort(key=lambda row: -1.0 if np.isnan(row[2]) else row[2], reverse=True)

        print(f"\n-- {axis} (baseline={BASELINE[axis]}) --")
        for value, cta, asr, tag in rows:
            marker = " <- baseline" if tag == "baseline" else ""
            print(f"  {axis}={value!r:<20} CTA={fmt(cta):>8} ASR={fmt(asr):>8}{marker}")

        best_value, best_cta, best_asr, best_tag = rows[0]
        baseline_asr = baseline["asr"]
        improved = (
            not np.isnan(best_asr)
            and (np.isnan(baseline_asr) or best_asr > baseline_asr)
            and best_tag != "baseline"
        )
        best_per_axis[axis] = best_value if improved else BASELINE[axis]
        if improved:
            print(f"  => best: {axis}={best_value!r} (ASR {fmt(best_asr)} > baseline {fmt(baseline_asr)})")
        else:
            print(f"  => baseline value already best for this axis")
    return best_per_axis


def print_combined_candidate(best_per_axis, results):
    combined = {**BASELINE, **{k: v for k, v in best_per_axis.items() if v != BASELINE[k]}}
    changed = {k: v for k, v in best_per_axis.items() if v != BASELINE[k]}

    print("\n=== Combined candidate (greedy best-per-axis) ===")
    if not changed:
        print("No axis beat baseline -- baseline itself is the best config found.")
        return None
    print("Overrides vs baseline:", changed)
    print(
        "CAVEAT: this combination was never actually run -- the sweep is one-at-a-time, so it "
        "cannot see interactions between axes (e.g. a lower epsilon and a higher lambda_bd "
        "might not combine as well as each did alone). Treat this as a candidate for ONE "
        "follow-up confirmation cell, not a proven result."
    )
    return combined


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--generate-combined", action="store_true",
        help="write the combined candidate as a new sweep cell (tag 'combined_best')",
    )
    args = parser.parse_args()

    results = load_results()
    print_ranking(results)
    best_per_axis = print_axis_breakdown(results)
    combined = print_combined_candidate(best_per_axis, results)

    if args.generate_combined:
        if combined is None:
            print("\nNothing to generate: baseline already wins, no 'combined_best' cell needed.")
        else:
            paths, reason = generate_cell("combined_best", {k: v for k, v in combined.items() if v != BASELINE[k]}, SEEDS[0])
            if reason:
                print(f"\nREFUSED combined_best: {reason}")
            else:
                print(f"\nWrote combined_best cell ({len(paths)} configs):")
                for p in paths:
                    print(f"  {p}")
                print(
                    "\nAdd 'combined_best' to orchestrate_runs_trigger_joint_sweep_slurm.sh's "
                    "CELL_TAGS (or run its 3 configs by hand) to confirm it."
                )
