#!/bin/bash
###
# orchestrate_trigger_slurm.sh
#
# Full-chain Slurm launcher for the `federated_generate_labels_trigger`
# threat model (indirect coupling: labels optimised by trajectory matching,
# delta receiving gradient only through L_bd).
#
# Chain, one Slurm job per cell, with afterok barriers between phases:
#
#   [EXPERT]  train_expert                     (optional, shared -- see below)
#        |
#   [GEN]     federated_generate_labels_trigger
#        |
#   [FLIPS]   federated_select_flips
#        |
#   [USER]    federated_train_user
#
# The EXPERT phase is OFF by default. Expert checkpoints are a NUISANCE FACTOR
# that must be identical across the three threat-model campaigns for their
# comparison to isolate the formulation: produce them once, then point all
# three orchestrators at the same EXPERT_DIR.
#
# Usage:
#   SLURM_ACCOUNT=<account> ./orchestrate_trigger_slurm.sh            # submit
#   SLURM_ACCOUNT=<account> DRY_RUN=1 ./orchestrate_trigger_slurm.sh  # enumerate only
#   RUN_EXPERT=1 SLURM_ACCOUNT=<account> ./orchestrate_trigger_slurm.sh
#
# Configs are expected to already exist (generated by
# modules/federated_generate_labels_trigger/gen_configs.py). Every path is
# checked BEFORE anything is submitted: a missing config aborts the whole
# campaign rather than leaving a half-submitted dependency graph behind.
###

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="${BASE_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"
export BASE_DIR
cd "$BASE_DIR"

# shellcheck source=slurm_lib.sh
source "$SCRIPT_DIR/slurm_lib.sh"

# ---------------------------------------------------------------------------
# Campaign definition -- edit here.
# ---------------------------------------------------------------------------
CAMPAIGN="${CAMPAIGN:-trigger_v1}"
CONFIG_ROOT="${CONFIG_ROOT:-$BASE_DIR/experiments/$CAMPAIGN/trigger}"

SEEDS=(${SEEDS:-0 1 2})
BUDGETS=(${BUDGETS:-500 1500 5000})     # flip counts, must match select_flips' `budgets`
AGGS=(${AGGS:-mean trmean})

# Nuisance factors held fixed across the three campaigns -- change them here
# and in the two sibling orchestrators together, never in one alone.
NUM_POISONED="${NUM_POISONED:-3}"
NUM_HONESTS="${NUM_HONESTS:-7}"
CHECKPOINT_SAMPLING="${CHECKPOINT_SAMPLING:-uniform}"   # this module's default

RUN_EXPERT="${RUN_EXPERT:-0}"
EXPERT_CONFIG="${EXPERT_CONFIG:-$CONFIG_ROOT/train_expert.toml}"

DRY_RUN="${DRY_RUN:-0}"

# ---------------------------------------------------------------------------
# Per-phase resources. slurm_lib reads these globals at submission time, so
# they are set immediately before each submit_job_pool_slurm call.
# ---------------------------------------------------------------------------
EXPERT_TIME="${EXPERT_TIME:-1-00:00:00}"
GEN_TIME="${GEN_TIME:-1-00:00:00}"
FLIPS_TIME="${FLIPS_TIME:-02:00:00}"    # CPU-bound, short
USER_TIME="${USER_TIME:-1-00:00:00}"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
MISSING=0

require_config() {
    local path="$1"
    if [ ! -f "$path" ]; then
        echo "[CONFIG] missing: $path" >&2
        MISSING=$((MISSING + 1))
    fi
}

cell_tag() {   # seed budget agg -> a safe, collision-free name
    printf 's%s_b%s_%s_%svs%s' "$1" "$2" "$3" "$NUM_POISONED" "$NUM_HONESTS"
}

# ---------------------------------------------------------------------------
# Build the job lists (no submission yet -- every config is validated first).
# ---------------------------------------------------------------------------
GEN_JOBS=()
FLIPS_JOBS=()
USER_JOBS=()

for seed in "${SEEDS[@]}"; do
  for budget in "${BUDGETS[@]}"; do
    for agg in "${AGGS[@]}"; do
      tag="$(cell_tag "$seed" "$budget" "$agg")"

      gen_cfg="$CONFIG_ROOT/gen/${tag}.toml"
      flips_cfg="$CONFIG_ROOT/flips/${tag}.toml"
      user_cfg="$CONFIG_ROOT/user/${tag}.toml"

      require_config "$gen_cfg"
      require_config "$flips_cfg"
      require_config "$user_cfg"

      GEN_JOBS+=("python run_experiment.py $gen_cfg|trig_gen_${tag}")
      FLIPS_JOBS+=("python run_experiment.py $flips_cfg|trig_flips_${tag}")
      USER_JOBS+=("python run_experiment.py $user_cfg|trig_user_${tag}")
    done
  done
done

if [ "$RUN_EXPERT" = "1" ]; then
    require_config "$EXPERT_CONFIG"
fi

if [ "$MISSING" -gt 0 ]; then
    echo "[ABORT] $MISSING config(s) missing -- generate them first:" >&2
    echo "        python -m modules.federated_generate_labels_trigger.gen_configs" >&2
    exit 1
fi

echo "[PLAN] campaign=$CAMPAIGN module=federated_generate_labels_trigger"
echo "[PLAN] cells=${#GEN_JOBS[@]} (seeds=${#SEEDS[@]} x budgets=${#BUDGETS[@]} x aggs=${#AGGS[@]})"
echo "[PLAN] num_poisoned=$NUM_POISONED num_honests=$NUM_HONESTS checkpoint_sampling=$CHECKPOINT_SAMPLING"
echo "[PLAN] phases: $([ "$RUN_EXPERT" = 1 ] && echo 'EXPERT -> ')GEN -> FLIPS -> USER"
echo "[PLAN] total jobs = $(( ${#GEN_JOBS[@]} * 3 + (RUN_EXPERT == 1 ? 1 : 0) ))"

if [ "$DRY_RUN" = "1" ]; then
    echo "[DRY-RUN] nothing submitted."
    printf '[DRY-RUN] %s\n' "${GEN_JOBS[@]}"
    exit 0
fi

preflight_slurm || exit 1

# ---------------------------------------------------------------------------
# Submit, phase by phase, each phase gated on a barrier over the previous one.
# ---------------------------------------------------------------------------
DEP=""

if [ "$RUN_EXPERT" = "1" ]; then
    TIME_PER_TASK="$EXPERT_TIME"
    EXPERT_JOBS=("python run_experiment.py $EXPERT_CONFIG|trig_expert")
    submit_job_pool_slurm EXPERT_JOBS "expert" "" || exit 1
    barrier=$(submit_barrier_slurm "trig_barrier_expert" "afterok:$(join_job_ids "${SUBMITTED_JOB_IDS[@]}")") || exit 1
    DEP="afterok:$barrier"
    echo "[PHASE] EXPERT done -> barrier $barrier"
else
    echo "[PHASE] EXPERT skipped (RUN_EXPERT=0) -- expert checkpoints assumed present."
    echo "[PHASE] they MUST be the same ones used by the two sibling campaigns."
fi

TIME_PER_TASK="$GEN_TIME"
submit_job_pool_slurm GEN_JOBS "gen" "$DEP" || exit 1
gen_barrier=$(submit_barrier_slurm "trig_barrier_gen" "afterok:$(join_job_ids "${SUBMITTED_JOB_IDS[@]}")") || exit 1
echo "[PHASE] GEN submitted -> barrier $gen_barrier"

TIME_PER_TASK="$FLIPS_TIME"
submit_job_pool_slurm FLIPS_JOBS "flips" "afterok:$gen_barrier" || exit 1
flips_barrier=$(submit_barrier_slurm "trig_barrier_flips" "afterok:$(join_job_ids "${SUBMITTED_JOB_IDS[@]}")") || exit 1
echo "[PHASE] FLIPS submitted -> barrier $flips_barrier"

TIME_PER_TASK="$USER_TIME"
submit_job_pool_slurm USER_JOBS "user" "afterok:$flips_barrier" || exit 1
echo "[PHASE] USER submitted."

echo "[DONE] campaign $CAMPAIGN submitted; job ids in $LOG_DIR/jobids_*.txt"
echo "[DONE] follow with: squeue -u \$USER -o '%.10i %.30j %.8T %.10M %R'"